### ISSUE TITLE
Provide functionality to merge SeriesSets

### ISSUE THREAD

**Issue by fabxc** [prometheus/tsdb#10]
Currently we can query multiple SeriesSets via label selectors but cannot merge two of them together while eliminating duplicates.
Internally we have similar functionality, so this is merely about making it accessible. We mostly need this for federation where we can have multiple AND'ed selectors (e.g. `abc{de=~"fg"}`) which are OR'd together.

Either we provide an external method OR'ing SeriesSets or extend the querying interface to accept more complex selectors, which would generally be trees.

**Comment by Gouthamve** [comment]
Are you talking about exposing `mergedSeriesSet` and adding multiple series instead of just two?

Ref: https://github.com/fabxc/tsdb/blob/master/querier.go#L262-L267

**Comment by fabxc** [comment]
Yea, functionality-wise it's pretty much the same. Just that it is less
about merging time windows of the same series but about dropping duplicates.
The code will look pretty much the same. The tricky part is how to expose
this behavior to the user.

**Comment by Gouthamve** [comment]
Hmm not able to see what could be tricky. Can I implement something like: 
`MergeSeriesSet(series ....SeriesSet) SeriesSet` and send a PR? 
Either I am missing the point or I need to implement it to see the difficulty :/

Also, there is an implicit assumption that a `SeriesSet` will be giving `Series` in a sorted order, with sorting based on the labels. But I don't see it written anywhere in the interface definition.

**Comment by Gouthamve** [comment]
Hmm, now that I actually read it again, I understand what you mean. Do we need this complexity in PromQL? Or do we need this functionality at all?

I see that the use-case for this is if we want to graph two different metrics on the same graph. But isn't that being handled by Grafana? And for federation, we can do it the way its currently being done, get the instant vectors and dedupe.

**Comment by fabxc** [comment]
Yes, the sortedness is part of the definition – it's an invariant that's not always easy to achieve and not necessary in all use cases. In general though, it seems to be something worth holding up. It has not been written down yet because it caused me a fair bit of headache an I was going back and forth on it for a while.

The use case here is actually only federation on the Prometheus side. You can specify matching parameters for series and want the union of them if you specify multiple ones.
So now it gets tricky. Just returning a union of series will work, but take a look at #9, which is targeted at federation as well. If we have something like that, we'd like to return a set of `(label_set, last_sample)` rather than `(label_set, full_series)`.

So the question is how to enable the union functionality API wise. The difficulty is definitely not implementing but exposition.
Exposing said `MergeSeriesSet` might just be the right choice in the mean time. Or just releasing a Prometheus 2.0 alpha with the restriction that overlapping series selectors in federation requests will yield duplicates and defer the decision.

**Comment by Gouthamve** [comment]
Closing this as it has been implemented in Prometheus itself and any app that is using it can do this. Merging the series of several queries is an advanced feature and will be added only when requested. 

Please feel free to re-open if need this.
