### ISSUE TITLE
Fix block ranges

### ISSUE THREAD

**Issue by fabxc** [prometheus/tsdb#102]
Currently block ranges allow fine-grained configuration. Practically, this has little to no benefit for Prometheus. It adds a lot of complexity however when dealing with those blocks in other ways, for example backup procedures.

I propose switching to a time slicing approach where possible block ranges after different compaction levels are fixed, as well as their position in time. This prevents arbitrary overlapping and interleaving of blocks at a global level.

Suppose we want a maximum block size of 9 days, then our valid ranges are as follows:
* 9d
* 3d
* 24h
* 6h
* 2h

The largest range is aligned with the 0 timestamp (epoch in Prometheus), smaller ones are always aligned with their parent range. Thus compaction will always result in larger blocks fitting the slices.

This can still be configurable in TSDB, especially for tests, but should be hard-coded in the using application.
For Prometheus I would fix it to the above values.

Alignment with wall clock weeks would have been nice but not all that important. TSDB having no notion of wall clocks and Unix 0 not aligning with the beginning of a week would just require a bunch of number shifting that just doesn't seem worth it.

@Gouthamve @brian-brazil

**Comment by brian-brazil** [comment]
I'm okay with this change. The fewer configurables there are, the fwer red herrings there are for users to get caught up on.

**Comment by Gouthamve** [comment]
Hmm, one pitfall that needs to be handled is that if we have a retention of 10days, we might end up with 18days worth of data before deleting things.

While we could adjust the things according to the retention, we need to think about how to handle it if someone shuts down and restarts Prometheus with a new retention.

**Comment by Gouthamve** [comment]
Closed in #103
