### ISSUE TITLE
Mystery deadlock

### ISSUE THREAD

**Issue by fabxc** [prometheus/tsdb#11]
There's a deadlock that hits Prometheus servers under load some time within 12 hours typically. It is known to occur in servers that are never queried so is likely located in the write path.

Goroutine dumps show to be entirely useless as all waiting goroutines are waiting to acquire a lock.
Thus, it's most likely inconsistent locking order or exiting a locked procedure without unlocking again.

**Comment by fabxc** [comment]
Potentially found and fixed. Testing now.

**Comment by fabxc** [comment]
Seems to be solved. Closing. @beorn7, please let me know if you encounter it again.

**Comment by beorn7** [comment]
Sadly, I still see the deadlock (after the first compaction). Would it be helpful to take a goroutine dump? I even have two different servers in the same state, so overlapping the two dumps might help.

Unfortunately, I have absolutely no cycles left to help debugging myself.

**Comment by fabxc** [comment]
Can confirm, just had it as well before. Might well be it's yet again a new one.
Have to revisit the overall locking structure. Even though there aren't many, it's still too easy to cause one.

**Comment by fabxc** [comment]
It seems I'm incredibly talented at fixing the lock, even adding doc strings on how the two locks causing this again and again (in the same function) should be used – and soon after reintroducing the wrong locking order in the same place... fixing and trying again.

**Comment by fabxc** [comment]
Okay, seems we have encountered quite a few different ones showing very similar stack traces.
Now things ran pretty long but still deadlocked eventually. The problem seems to be when cutting a new block (B) and still writing to the previous one (A). That may happen simply because of weird concurrency interleaving but also if a single scrapes contains samples with timestamps across both blocks.

* P1 takes rlock for A, then rlock for B
* P2 takes rlock for A, then rlock for B
* P1 wants to create new series in A and attempts switching A's rlock to a wlock
* P2 wants to create new series in B and attempts switching B's rlock to a wlock

Result: deadlock

Looking for a non-hacky solution now. 

Lesson here: optimizing lock contention makes adding deadlocks really easy.

**Comment by fabxc** [comment]
A workaround was pushed that generally works for Prometheus, where every write transaction only appends samples of the same timestamp. This was done to unblock a first alpha release of the storage.

Generally, the full behavior can be restored without any predicted performance impact but should be done carefully with a clean design. We might have to drop the property of nested `Appender` to gain more control of the locking order.
