### ISSUE TITLE
Export the oldest timestamp in the db

### ISSUE THREAD

**Issue by Gouthamve** [prometheus/tsdb#113]
This would help us query the remote storage from the correct timestamp and also enable other use-cases such as https://github.com/prometheus/prometheus/issues/2988

This is trivial to implement as it would be a method on `*DB` where we just return the `MinTime` of the oldest block.

**Comment by Gouthamve** [comment]
@ventris Do you want to give this a shot? This is actually quite simple and would help you understand the structure.

The `*DB` object has a list of blocks and each block exposes it `MinTime` and `MaxTime`. So it would be easy to expose that.

**Comment by ventris** [comment]
Yes, I will give this a shot.

**Comment by krasi-georgiev** [comment]
@ventris , @Gouthamve is it ok to take this one ?

**Comment by Gouthamve** [comment]
There is this PR open to address this I think: https://github.com/prometheus/tsdb/pull/134

**Comment by krasi-georgiev** [comment]
@Gouthamve that is against master , will it get merged to dev-2.0 as well?

**Comment by Gouthamve** [comment]
Yes, this is the storage engine used by dev-2.0.

So the master of this repo (prometheus/tsdb) is vendored into the dev-2.0 of the prometheus/prometheus repo. If you are looking for issues to pick, I am happy to provide pointers for #107

**Comment by krasi-georgiev** [comment]
@Gouthamve great , I will read the info and ping you if I need any pointers.

**Comment by ventris** [comment]
@krasi-georgiev yes please go ahead, I haven't had the time to begin.

**Comment by Gouthamve** [comment]
Closed in #134 and #152
