### ISSUE TITLE
is it a bug?

### ISSUE THREAD

**Issue by qinguoan** [prometheus/tsdb#114]
a.activeWriters maybe decrease twice when commit error ?

> func (a *headAppender) Commit() error {
	defer atomic.AddUint64(&a.activeWriters, ^uint64(0))
	defer putHeadAppendBuffer(a.samples)
	defer a.mtx.RUnlock()

> func (a *headAppender) Rollback() error {
	a.mtx.RUnlock()
	atomic.AddUint64(&a.activeWriters, ^uint64(0))

**Comment by fabxc** [comment]
You mean if we call Rollback() after a failed Commit(). 
The intended usage would be that a failed commit is irrecoverable and equivalent to a Rollback, i.e. calling Rollback after a failed Commit would be wrong. I suppose that needs clearer documentation.

**Comment by qinguoan** [comment]
Got, thanks
