### ISSUE TITLE
Seg Faults in tsdb.(*querier).Select

### ISSUE THREAD

**Issue by johrstrom** [prometheus/tsdb#117]
Hi, we're getting a lot of segfaults at this location.  I do not know how to find the block it's attempting to sort or how I would un-encode it if I did.  I also do not know the query it's trying to serve.  This is coming from Prometheus (a query made through the API) as you see at the bottom of the stack given, but I figured it would be more appropriate here. I can provide the rest of the stack if you wish, but it seemed irrelevant. 

```
Aug 07 21:01:36 ip prometheus[89622]: unexpected fault address 0x7f15d925dd8c
Aug 07 21:01:36 ip prometheus[89622]: fatal error: fault
Aug 07 21:01:36 ip prometheus[89622]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x7f15d925dd8c pc=0x45ab09]
Aug 07 21:01:36 ip prometheus[89622]: goroutine 2897513 [running]:
Aug 07 21:01:36 ip prometheus[89622]: runtime.throw(0x1c0ab5d, 0x5)
Aug 07 21:01:36 ip prometheus[89622]:         /usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xca7ab12520 sp=0xca7ab12500
Aug 07 21:01:36 ip prometheus[89622]: runtime.sigpanic()
Aug 07 21:01:36 ip prometheus[89622]:         /usr/local/go/src/runtime/signal_unix.go:297 +0x28c fp=0xca7ab12570 sp=0xca7ab12520
Aug 07 21:01:36 ip prometheus[89622]: runtime.cmpbody()
Aug 07 21:01:36 ip prometheus[89622]:         /usr/local/go/src/runtime/asm_amd64.s:1586 +0xf9 fp=0xca7ab12578 sp=0xca7ab12570
Aug 07 21:01:36 ip prometheus[89622]: sort.(*StringSlice).Less(0xc58eb8b5a0, 0x0, 0x1f1, 0x400)
Aug 07 21:01:36 ip prometheus[89622]:         <autogenerated>:13 +0x8e fp=0xca7ab125b8 sp=0xca7ab12578
Aug 07 21:01:36 ip prometheus[89622]: sort.doPivot(0x2859dc0, 0xc58eb8b5a0, 0x0, 0x8b7, 0xca7ab126a8, 0x41218c)
Aug 07 21:01:36 ip prometheus[89622]:         /usr/local/go/src/sort/sort.go:123 +0x157 fp=0xca7ab12650 sp=0xca7ab125b8
Aug 07 21:01:36 ip prometheus[89622]: sort.quickSort(0x2859dc0, 0xc58eb8b5a0, 0x0, 0x8b7, 0x18)
Aug 07 21:01:36 ip prometheus[89622]:         /usr/local/go/src/sort/sort.go:192 +0x80 fp=0xca7ab126b0 sp=0xca7ab12650
Aug 07 21:01:36 ip prometheus[89622]: sort.Sort(0x2859dc0, 0xc58eb8b5a0)
Aug 07 21:01:36 ip prometheus[89622]:         /usr/local/go/src/sort/sort.go:220 +0x79 fp=0xca7ab126f0 sp=0xca7ab126b0
Aug 07 21:01:36 ip prometheus[89622]: sort.Strings(0xcc81e64000, 0x8b7, 0xa00)
Aug 07 21:01:36 ip prometheus[89622]:         /usr/local/go/src/sort/sort.go:351 +0x6d fp=0xca7ab12738 sp=0xca7ab126f0
Aug 07 21:01:36 ip prometheus[89622]: github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*headIndexReader).LabelValues(0xc43b3a8538, 0xcc6118d570, 0x1, 0x1, 0x0, 0x0, 
Aug 07 21:01:36 ip prometheus[89622]:         /opt/aeg/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/head.go:679 +0x240 fp=0xca7ab12820 sp=0xca7ab12738
Aug 07 21:01:36 ip prometheus[89622]: github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*postingsReader).selectSingle(0xca7ab12aa0, 0x284b380, 0xc58eb8b080, 0x1, 0x2)
Aug 07 21:01:36 ip prometheus[89622]:         /opt/aeg/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/querier.go:235 +0x1e3 fp=0xca7ab12950 sp=0xca7ab12820
Aug 07 21:01:36 ip prometheus[89622]: github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*postingsReader).Select(0xca7ab12aa0, 0xc627653940, 0x4, 0x4, 0x285ac80, 0xca7
Aug 07 21:01:36 ip prometheus[89622]:         /opt/aeg/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/querier.go:215 +0x104 fp=0xca7ab12a18 sp=0xca7ab12950
Aug 07 21:01:36 ip prometheus[89622]: github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*blockQuerier).Select(0xc7fbecc640, 0xc627653940, 0x4, 0x4, 0x2851480, 0xc6276
Aug 07 21:01:36 ip prometheus[89622]:         /opt/aeg/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/querier.go:144 +0x9e fp=0xca7ab12ac0 sp=0xca7ab12a18
Aug 07 21:01:36 ip prometheus[89622]: github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*querier).sel(0xc58eb8ad40, 0xc58eb8ad30, 0x1, 0x1, 0xc627653940, 0x4, 0x4, 0x
Aug 07 21:01:36 ip prometheus[89622]:         /opt/aeg/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/querier.go:113 +0x1d8 fp=0xca7ab12b30 sp=0xca7ab12ac0
Aug 07 21:01:36 ip prometheus[89622]: github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*querier).sel(0xc58eb8ad40, 0xc58eb8ad20, 0x2, 0x2, 0xc627653940, 0x4, 0x4, 0x
Aug 07 21:01:36 ip prometheus[89622]:         /opt/aeg/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/querier.go:116 +0x142 fp=0xca7ab12ba0 sp=0xca7ab12b30
Aug 07 21:01:36 ip prometheus[89622]: github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*querier).Select(0xc58eb8ad40, 0xc627653940, 0x4, 0x4, 0x0, 0x4)
Aug 07 21:01:36 ip prometheus[89622]:         /opt/aeg/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/querier.go:104 +0x64 fp=0xca7ab12bf8 sp=0xca7ab12ba0
Aug 07 21:01:36 ip prometheus[89622]: github.com/prometheus/prometheus/storage/tsdb.querier.Select(0x285ad40, 0xc58eb8ad40, 0xc58eb8ab40, 0x4, 0x4, 0x20, 0x20)
Aug 07 21:01:36 ip prometheus[89622]:         /opt/aeg/go/src/github.com/prometheus/prometheus/storage/tsdb/tsdb.go:97 +0x1be fp=0xca7ab12c98 sp=0xca7ab12bf8
Aug 07 21:01:36 ip prometheus[89622]: github.com/prometheus/prometheus/storage/tsdb.(*querier).Select(0xcc4042fba0, 0xc58eb8ab40, 0x4, 0x4, 0x0, 0xc9cf239500)
Aug 07 21:01:36 ip prometheus[89622]:         <autogenerated>:4 +0x74 fp=0xca7ab12ce0 sp=0xca7ab12c98
Aug 07 21:01:36 ip prometheus[89622]: github.com/prometheus/prometheus/promql.(*Engine).populateIterators.func2(0x7f17be647150, 0xc543da8ee0, 0x3bff6c43a35)
Aug 07 21:01:36 ip prometheus[89622]:         /opt/aeg/go/src/github.com/prometheus/prometheus/promql/engine.go:529 +0x504 fp=0xca7ab12dc8 sp=0xca7ab12ce0
Aug 07 21:01:36 ip prometheus[89622]: github.com/prometheus/prometheus/promql.inspector.Visit(0xc879b0db30, 0x7f17be647150, 0xc543da8ee0, 0x7f17be647150, 0x1971b20)
Aug 07 21:01:36 ip prometheus[89622]:         /opt/aeg/go/src/github.com/prometheus/prometheus/promql/ast.go:306 +0x3a fp=0xca7ab12df0 sp=0xca7ab12dc8
Aug 07 21:01:36 ip prometheus[89622]: github.com/prometheus/prometheus/promql.Walk(0x2846f00, 0xc879b0db30, 0x7f17be647150, 0xc543da8ee0)
```
Prometheus Version Info.  I went a head and checked that the last time Prometheus updated the vendor/github.com/prometheus/tsdb was the commit before this one. 

prometheus, version 2.0.0-beta.0 (branch: dev-2.0, revision: 2b5d9159537cbd123219296121e05244e26c0940)
  build user:       jeff@localhost.localdomain
  build date:       20170712-22:36:27
  go version:       go1.8

Please let me know if you need more information.

**Comment by johrstrom** [comment]
@fabxc @brian-brazil I apologize if I should have opened this against Prometheus and not the tsdb sub component.  Please let me know if you want me move it.

**Comment by fabxc** [comment]
All good. Based on the stack trace this is in the right place.
Thanks for reporting.

**Comment by fabxc** [comment]
So this is a really odd one to be honest. `sort.Sort` is known to panic for semantically incorrect comparison function. However, here we have a string slice and are sorting with the `sort.Strings` function. Strings in the input list cannot even be nil.

I'm lost on what could possibly cause this – also haven't seen it anywhere else before.
Can you reliably reproduce this and possibly print the input to the sorting?

**Comment by johrstrom** [comment]
This happens to me often, so I can definitely replicate.  After looking through the code, I'm guess I should print the [array here](https://github.com/prometheus/tsdb/blob/master/head.go#L679)?  I'll try to get the patch deployed in my env and let you know. 

By the way, I don't believe any of them are nil, isn't that a different error message (invalid memory address or nil pointer dereference?). 

I'll also have to look into where this is happening in a GC cycle. Could it be that while sorting it's referencing a label value that got GC'd? As I say it, it doesn't sound right, but it was my initial thought when I first saw it.

**Comment by fabxc** [comment]
Yea right, that's typically something about invalid memory.
Generally, a referenced value can by definition not be GC'd.

The first guess where we could see this of course would be mmap'd memory. But this occurs in the headIndexReader which purely deals with heap memory.

Second guess would be that it's something caused by Prometheus' retrieval layer playing a few `unsafe` tricks to prevent loads of memory allocations. But strings we actually pass down to the storage are properly allocated as regular strings.
If we messed this up somewhere, I'd expect this to be a very frequent issue but neither ourselves nor anyone else has reported something like this before.
Also quite unlikely that this would be the first (and only?) place where the issue shows.

Is there anything out of the ordinary about your environment? (Architecture, OS, ...)

**Comment by johrstrom** [comment]
```Is there anything out of the ordinary about your environment? (Architecture, OS, ...)```
I can't image so, we're running CoreOS (1409.7.0 (Ladybug), kernel 4.11.11-coreos) in Amazon as a r4.4xlarge type. 

This query is around 280k, which I'm sure others have surpassed. 
```rate(tsdb_samples_appended_total{}[1m])```

```this would be the first (and only?) place where the issue shows.```
Good question! It runs out labels are all f**ed up for me. I went back and found I'm getting stacks in at least 2 other places all related to labels, so perhaps this does need to go to the prometheus main project. 

```
unexpected fault address 0x7f9397b2b603
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f9397b2b603 pc=0x45a91a]
goroutine 213 [running]:
runtime.throw(0x1c0ab5d, 0x5)
        /usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc52dda7558 sp=0xc52dda7538
runtime.sigpanic()
     /usr/local/go/src/runtime/signal_unix.go:297 +0x28c fp=0xc52dda75a8 sp=0xc52dda7558
runtime.memeqbody()
         /usr/local/go/src/runtime/asm_amd64.s:1457 +0x8a fp=0xc52dda75b0 sp=0xc52dda75a8
github.com/prometheus/prometheus/pkg/labels.(*Builder).Set(0xc52dda76b8, 0x7f9397b2b603, 0x9, 0x7f93976f97f7, 0x5, 0xc52dda76b8)
        /opt/aeg/go/src/github.com/prometheus/prometheus/pkg/labels/labels.go:222 +0x1d2 fp=0xc52dda7628 sp=0xc52dda75b0
 github.com/prometheus/prometheus/rules.(*AlertingRule).sample(0xc5aacbe300, 0xc542415c00, 0xed118293b, 0xc50df21662, 0x291c580, 0x0, 0
      /opt/aeg/go/src/github.com/prometheus/prometheus/rules/alerting.go:138 +0x1e9 fp=0xc52dda7710 sp=0xc52dda7628
 github.com/prometheus/prometheus/rules.(*AlertingRule).Eval(0xc5aacbe300, 0x7f941f499000, 0xc6524585c0, 0xed118293b, 0xdf21662, 0x291c
        /opt/aeg/go/src/github.com/prometheus/prometheus/rules/alerting.go:263 +0x10ba fp=0xc52dda79f0 sp=0xc52dda7710
github.com/prometheus/prometheus/rules.(*Group).Eval.func1(0x1c0f3b5, 0x8, 0xc5aacbe800, 0xed118293b, 0xc80df21662, 0x291c580, 0x3, 0x
        /opt/aeg/go/src/github.com/prometheus/prometheus/rules/manager.go:306 +0x177 fp=0xc52dda7d58 sp=0xc52dda79f0
github.com/prometheus/prometheus/rules.(*Group).Eval(0xc5aacbe800, 0xed118293b, 0xdf21662, 0x291c580)
        /opt/aeg/go/src/github.com/prometheus/prometheus/rules/manager.go:374 +0x10b fp=0xc52dda7dd8 sp=0xc52dda7d58
 github.com/prometheus/prometheus/rules.(*Group).run.func1()
        /opt/aeg/go/src/github.com/prometheus/prometheus/rules/manager.go:181 +0x7e fp=0xc52dda7e28 sp=0xc52dda7dd8
github.com/prometheus/prometheus/rules.(*Group).run(0xc5aacbe800)
        /opt/aeg/go/src/github.com/prometheus/prometheus/rules/manager.go:206 +0x328 fp=0xc52dda7fa8 sp=0xc52dda7e28
github.com/prometheus/prometheus/rules.(*Manager).ApplyConfig.func1.1(0xc652458600, 0xc5aacbe800)
        /opt/aeg/go/src/github.com/prometheus/prometheus/rules/manager.go:509 +0x52 fp=0xc52dda7fd0 sp=0xc52dda7fa8
```

and 
```
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f2b8e9a8868 pc=0x45a91a]
goroutine 120 [running]:
runtime.throw(0x1c0ab5d, 0x5)
         /usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc580df87f8 sp=0xc580df87d8
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:297 +0x28c fp=0xc580df8848 sp=0xc580df87f8
runtime.memeqbody()
        /usr/local/go/src/runtime/asm_amd64.s:1457 +0x8a fp=0xc580df8850 sp=0xc580df8848
type..eq.github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.term(0xc580df8910, 0xca4e7fc778, 0x6dcc808e2c3db0a3)
        /opt/aeg/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/block.go:1 +0xa4 fp=0xc580df8888 sp=0xc580
runtime.mapaccess1(0x1974f40, 0xc97920b9b0, 0xc580df8910, 0x1ace400)
         /usr/local/go/src/runtime/hashmap.go:348 +0x19e fp=0xc580df88d0 sp=0xc580df8888
github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*headIndexReader).Postings(0xc47989fb30, 0xc99d80a87d, 0x9, 0xc99
        /opt/aeg/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/head.go:689 +0xf2 fp=0xc580df8940 sp=0xc58
 github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*postingsReader).selectSingle(0xc580df8bc0, 0x284b300, 0xc9287ac0
        /opt/aeg/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/querier.go:226 +0xa1 fp=0xc580df8a70 sp=0x
 github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*postingsReader).Select(0xc580df8bc0, 0xc435c86570, 0x3, 0x3, 0x2
       /opt/aeg/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/querier.go:215 +0x104 fp=0xc580df8b38 sp=0
 github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*blockQuerier).Select(0xc68dee3270, 0xc435c86570, 0x3, 0x3, 0x285)
```

I think it may be related to this new alertmanager relabel config feature (given the rule generation stack above).  I've deploy [kube state metrics](https://github.com/kubernetes/kube-state-metrics) and I'm changing the exported_namespace (that I get from it) into just namespace, but only for alerting.  Kube state metrics itself has a namespace, which I don't change during actual ingestion.  

```
  alert_relabel_configs:
  - source_labels: [exported_namespace]
    regex: (.+)
    action: replace
    target_label: namespace
```

I'm going to try replacing replacing them during scrape ingestion instead of during alerting.  Perhaps if it stops seg faulting, and if so, it'll clearly be a problem with alert manager relabeling.

**Comment by fabxc** [comment]
First, great to see that someone is testing 2.0 with such a rather heavy load!

The only touching point of alert relabel configs is that it gets its label from the storage. There's no dependency in the other direction.
So if the issue also occurs in the storage first, the cause is more likely to be somewhere in the storage.

I would say that testing it on another instance might be interesting since the hardware memory might be messed up somehow. But since it only occurs for labels, that's a rather unlikely guess.

I currently have  the last beta and the current HEAD running on AWS at 220k samples/sec with rahter heavy querying load. I do not see any panics.

**Comment by johrstrom** [comment]
This issue persists, but I'm going to update to 2.0.0-beta.1 that was just released and we'll see what's happening. We're also going to re-architect a little bit (for sharding reasons) so maybe, if it persists that'll shed some light on it. 

Also I was thinking it could have something to do with empty or null labels?  I have ec2 discovery where I'm trying to build a label out of ec2 tags and they're only present maybe 95% of the time. 

Lastly, ```testing it on another instance``` only confirms what you suspect. We're running a pair behind a load balancer and they seg fault seconds apart from each other, I guess because the LB makes the duplicate query on the second one. 

In any case, when I update and restructure the deployment, I'll let you know what happens either way.

**Comment by johrstrom** [comment]
I upgraded to ```beta-2.2``` and seemed to have traded this for [issue 2955](https://github.com/prometheus/prometheus/issues/2955). I'm going to close this issue now.

**Comment by Gouthamve** [comment]
This is back again? See prometheus/prometheus#3217

**Comment by johrstrom** [comment]
I just installed beta.5 on Friday and let it run over the weekend, and surprisingly I didn't see it happen. If it does, I'll update this ticket (or the other). Otherwise, no news is good news.

version info:
prometheus, version 2.0.0-beta.5 (branch: HEAD, revision: )
  build user:       root@df40cc0bd79b
  build date:       20170921-16:23:04
  go version:       go1.8.3

**Comment by fabxc** [comment]
Underlying issue got fixed.
