### ISSUE TITLE
Missing data for format string 'open WAL %s'

### ISSUE THREAD

**Issue by ankon** [prometheus/tsdb#125]
See https://github.com/prometheus/tsdb/blob/e0aca4bee9ae472d1c164c5562eed2a4bf4c700a/db.go#L880: there is no value given for the %s, so it appears literally in the log output.

**Comment by Gouthamve** [comment]
Oops, but luckily it is an easy fix. We just need to pass the folder name to `%s`.

Do you want to send a PR for that @ankon ?

**Comment by ankon** [comment]
I tried in #126, by looking at the surrounding code and guessing a bit that the directory parameter given in is probably more useful than the specific `{dir}/wal` calculated in the function :)
