### ISSUE TITLE
Add 'table of contents' to index file

### ISSUE THREAD

**Issue by fabxc** [prometheus/tsdb#13]
An entry at the end of the index file documenting where the main sections start (and end) would help making analysis easier. For example, all postings lists of the inverted indices are currently stored uncompressed, which unexpectedly has very little size overhead.
Having better understanding what is how expensive size-wise, makes prioritising improvements easier.

Currently all references/offsets to entries in index or chunk files are stored as absolute positions of those files. One consideration was making them relative to start of their respective section. This needs said TOC in the index file as a prerequisite.

**Comment by Gouthamve** [comment]
Do you have any ideas on how the TOC should look? Or should I take a rough stab at this?

**Comment by Gouthamve** [comment]
@fabxc Can this be closed now?

**Comment by fabxc** [comment]
Indeed.
