### ISSUE TITLE
unified WAL rather than per block

### ISSUE THREAD

**Issue by Gouthamve** [prometheus/tsdb#131]
Due to large amount of lock contention, we maybe moving to a unified WAL (as well as a single in-mem datastructure rather than several head-blocks).

```
// WAL is a write ahead log that can log new series labels and samples.
// It must be completely read before new entries are logged.
type WAL interface {
Reader() WALReader
LogSeries([]labels.Labels) error
LogSamples([]RefSample) error
LogDeletes([]Stone) error
Truncate(int64)
Close() error
}
```

We just keep appending to the WAL and whenever the database chugs out a persistent block, it will call the `Truncate(mint)` function and we need to drop any old segment files and also mark the overlapping segment file so that we only read the values after `mint`.

I think allocating the first 16bytes of each segment file to store the `mint, maxt` would allow for most things. When reading the WAL back, we just look at the `mint` and then read only the values that popup after `mint`.

Another issue is that the `labels --> seriesID` entry could be in the first WAL segment and if the series never expires, then we might be dropping the `seriesID` entry when we drop the first segment. For that the alternate is to dump the active series everytime a new block is cut. Do we want to extend `Truncate(int64)` to `Truncate(int64, series)`?

@fabxc

**Comment by fabxc** [comment]
>  think allocating the first 16bytes of each segment file to store the mint, maxt would allow for most things. When reading the WAL back, we just look at the mint and then read only the values that popup after mint.

I think we don't have to store it at all. On startup we read each segment and thereby have to compute the ranges anyway.
On any segments written afterwards, we can also compute it easily. So keeping it in memory should be sufficient.

> Another issue is that the labels --> seriesID entry could be in the first WAL segment and if the series never expires, then we might be dropping the seriesID entry when we drop the first segment. For that the alternate is to dump the active series everytime a new block is cut. Do we want to extend Truncate(int64) to Truncate(int64, series)?

Yea so a dump file is the easy option I think. It could just be a WAL file as well which just has serie s entries and which we give the first ordinal file name before the remaining segments.

Probably `Truncate(mint int64, exits func(id uint32) bool) error` is the saner option as we don't have to pass a list of series. Though an iterator (`Postings`) could work as well.

**Comment by fabxc** [comment]
This is in master.
