### ISSUE TITLE
headAppender.Add() produces duplicate refs for different label-sets, causing prometheus to crash

### ISSUE THREAD

**Issue by igorcanadi** [prometheus/tsdb#137]
Please take a look at the issue https://github.com/prometheus/prometheus/issues/2955 and specifically the comment https://github.com/prometheus/prometheus/issues/2955#issuecomment-327314624. Would really appreciate your help in tracking this down.

**Comment by Gouthamve** [comment]
One way this could happen is when new blocks are cut. But there are changes in the `nohead` branch that should fix this.

**Comment by fabxc** [comment]
This is fixed.
