### ISSUE TITLE
add vendor to this project

### ISSUE THREAD

**Issue by timchenxiaoyu** [prometheus/tsdb#145]
some package need to download ,please add vendor

**Comment by fabxc** [comment]
In general this repository is a library and not a full application. A command line tool exists but in a very early state. In general, libraries should not have `vendor/` directories in Go.

**Comment by Gouthamve** [comment]
Closing this as won't fix. As said above, this is a lib and its highly unlikely we will add a vendor folder. But if you have good reasons for a vendor folder, please feel free to re-open.
