### ISSUE TITLE
Use fast access to postings depending on label matcher type

### ISSUE THREAD

**Issue by fabxc** [prometheus/tsdb#19]
This TODO in the querier points out an important optimization: https://github.com/fabxc/tsdb/blob/a4be181d3cb836e7e77a412374f19230cfc9cf46/querier.go#L165-L177

Currently we take a label matcher, iterate over all values for the label and add all matching values to our matching result. We than lookup all postings lists for the result label/value pairs.
This is necessary for regexes or potentially user-defined matchers. But for the base matchers we define, we can do better – in particular for a trivial equality matcher.

We can try to upgrade the matcher interface to the equality matcher and then skip the iteration all together and just lookup the postings list directly.

That saves a lot of time when equality matching high-cardinality labels such as the instance label.

Later, one could do similar things for regexp matching. A lot of regexp matchers have a fixed prefix, which could be extracted to limit the total range of label values that are matched against the total regexp. This works because the label value index is sorted.

@Gouthamve the first part is a low hanging fruit.

**Comment by dilyevsky** [comment]
Looks like this is still relevant? Can I take this?

**Comment by fabxc** [comment]
Sure, that would be great.
I think we converged towards adding new matcher types for sets and prefixes to prometheus/tsdb and then add separate functions to actually disassemble a regex and creating set and prefix matcher types out of those.

**Comment by dilyevsky** [comment]
So I just got to this... I can see the first part (direct posting lookup for equal matcher) is done. What are "set matchers" supposed to be exactly? Can you point me to the discussion?

Also I assume you mean some simple heuristic for regex prefix extraction? e.g. only optimize regex or the form "^abc" or something like that? I tried to read up on regex index search optimization but couldn't find much info...

**Comment by Gouthamve** [comment]
Hey, so it was decided that we should not add optimisations to the regexp-matcher but rather create new matchers and have prometheus parse its queries and send in the correct matcher kind into tsdb. For example if `^abc` was given to prometheus, then it will send in `NotMatcher(abc)`.

So one thing you can do is to add a prefix [matcher](http://godoc.org/github.com/prometheus/tsdb/labels#Matcher) like the [Equal](https://github.com/prometheus/tsdb/blob/master/labels/selector.go#L54) and [Regexp](https://github.com/prometheus/tsdb/blob/master/labels/selector.go#L68) matchers.

For example, the prefix matcher with the prefix: `abc` will match the strings `abcd`, `abccc` and so on.

Once this matcher is added, we can actually optimise the queries that are like `{path~="/users"}` in prometheus to detect prefix matching and send it down to tsdb.

Let me know if anything is unclear or if you have any doubts while implementing.

**Comment by cstyan** [comment]
Should this still be open? Looks like the prefix matcher was added.

**Comment by krasi-georgiev** [comment]
Yes I think can be closed now.
