### ISSUE TITLE
Handle partial writes in WAL

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/tsdb#217]
Currently the WAL is not resilient to partial writes, and thus can be corrupted if a machine dies.

Any data written before a sync completes may only have arbitrary parts of it actually written out to disk. To contract this, the simplest solution would be after a sync to write a marker that up to this point in the WAL is good, and then sync again so that marker is written out.

@Gouthamve What we were discussing last night.

**Comment by Gouthamve** [comment]
Yes, so we do handle this: https://github.com/prometheus/tsdb/blob/master/wal.go#L1087-L1125

Any data is de-serialized only if the checksum matches and any partial write errors while reading back.
