### ISSUE TITLE
Feature request: Snapshot names without colon

### ISSUE THREAD

**Issue by robfig** [prometheus/tsdb#221]
Colon in a filename trips up linux tools like ssh, scp, and tar ([shockingly](http://steve-parker.org/linux/tar-colon-filename/)). As a result, writing the script to archive, copy between systems, and restore a snapshot took 3x longer than it had to. I'd propose changing the name format for snapshots to be more script-friendly

**Comment by SuperQ** [comment]
Also, colon is completely incompatible with Windows.

**Comment by brian-brazil** [comment]
This issue should be against Prometheus: https://github.com/prometheus/prometheus/blob/master/web/api/v1/api.go#L641

**Comment by robfig** [comment]
Moved there!
