### ISSUE TITLE
Make absent use a generated postings list | New Matcher interface

### ISSUE THREAD

**Issue by Gouthamve** [prometheus/tsdb#223]
Right now we have absent selector, which just selects all the series without that selector and then removes the series that have the label set. This is ugly and can select ALL series if the query is just consisting of absent selectors.

https://github.com/prometheus/tsdb/blob/master/querier.go#L214 and https://github.com/prometheus/tsdb/blob/master/querier.go#L483-L487

Instead can we use a generated PostingsList for the series w/o the labels? This could just get the [`allPostings`](https://github.com/prometheus/tsdb/blob/df4657bcc5bff871816c636aa3b610ef3d421163/postings.go#L84) list and then remove the series that contain the label. As the evaluation is lazy, it should not be too hard.

-----------------------------

This comes in the wake of https://github.com/prometheus/prometheus/issues/3575 and the [`Matcher`](https://github.com/prometheus/tsdb/blob/master/labels/selector.go#L35-L40) interface we have doesn't let us have matchers which are not bound to a label. Can we change the interface to make it more powerful?

**Comment by brian-brazil** [comment]
> This is ugly and can select ALL series if the query is just consisting of absent selectors.

Such a selector is invalid, as it's too easy to do that by accident.

**Comment by Gouthamve** [comment]
Closed by #228
