### ISSUE TITLE
releases for tsdb in sync with prometheus

### ISSUE THREAD

**Issue by gouthamve** [prometheus/tsdb#232]
@TheTincho mentioned that tsdb should also have tagged releases which makes it easy for him to package. For that and otherwise, I think it makes sense to tag tsdb with every prometheus release too.

**Comment by krasi-georgiev** [comment]
@gouthamve lets discuss this on the next dev monthly call?

**Comment by gouthamve** [comment]
+1

**Comment by krasi-georgiev** [comment]
we already started doing tags and will also add a changelog file so this should be enough for now.
