### ISSUE TITLE
Merging of smaller-chunks during compaction

### ISSUE THREAD

**Issue by gouthamve** [prometheus/tsdb#236]
There should be an option passed to the compactor that will let us merge smaller chunks into larger ones while compacting.

**Comment by krasi-georgiev** [comment]
What is the use case for this?

**Comment by gouthamve** [comment]
Well it needs to be investigated (aka benchmarked) but having larger chunks would be more efficient and also, because when we query for larger range, we end up reading all the chunks anyways, so it should only help, not hurt.

But again, this is all guess work and needs to be benchmarked to be verified.

**Comment by krasi-georgiev** [comment]
understood, thanks! 
added the appropriate labels.

**Comment by csmarchbanks** [comment]
I am planning to investigate/work on this

**Comment by krasi-georgiev** [comment]
thanks, appreciated!

for this we would also need to implement some sort of benchmarking to compare the before and after results.

related to: https://github.com/prometheus/tsdb/issues/235

**Comment by csmarchbanks** [comment]
Yep, I was planning to start with some regular go benchmarks, but will keep my eyes on #235.

Also, any opinions on "smaller into larger chunks"? It looks like head tries to make chunks with 120 samples in each, should that still be the goal, or should we make even bigger chunks?

**Comment by krasi-georgiev** [comment]
I think @gouthamve's idea was that we increase the size during compaction and leave the default ones as they are. 

Again to make this worth merging we need to see some good improvements to justify the extra code.

**Comment by csmarchbanks** [comment]
I finally got some time to do some benchmarking of this. There is an initial PR up at #397.

It looks like there is quite a query performance improvement by making larger chunks. However, I am not sure how large of chunks to make? Right now the PR is going from ~120 -> 480 samples.

**Comment by csmarchbanks** [comment]
We should probably close this since the investigation did not pan out.

**Comment by gouthamve** [comment]
👍 Not worth it
