### ISSUE TITLE
Use clearer, more verbose variable names

### ISSUE THREAD

**Issue by shubheksha** [prometheus/tsdb#237]
Using one character variable names without any context/comments makes it really hard to understand what's going on in the code. For example, consider the following block of code:
https://github.com/prometheus/tsdb/blob/07ef80820ef1250db82f9544f3fcf7f0f63ccee0/head.go#L480-L493

**Comment by krasi-georgiev** [comment]
yep I completely agree, single letters are fine in some cases, but unless it is really clear I would also prefer a more descriptive namingz.


I am closing this now since we don't need an issue for this, but feel free to open a PR and I will happily review.

**Comment by krasi-georgiev** [comment]
actually it might be useful to keep it open for someone looking to pick up a task.

**Comment by palash25** [comment]
Hi there I am looking for a beginner issue, can I claim this?

**Comment by krasi-georgiev** [comment]
that would be great , thanks!

**Comment by krasi-georgiev** [comment]
short variable names are fine if they are used in the next 1-2 lines , otherwise something more descriptive would be easier to follow.

**Comment by krasi-georgiev** [comment]
this is stale now so closing and if anyone feels like improving the variable names feel free to open a PR and I will review.
