### ISSUE TITLE
Align series to 8/16byte padding to increase addressable space

### ISSUE THREAD

**Issue by Gouthamve** [prometheus/tsdb#238]
https://github.com/prometheus/prometheus/issues/3190 is because we store the offset to series data in the index and we store in a `uint32` giving us only 4GB of addressable space.

To increase it, we can use an `uint64` but that would double the postings space required and compression would mean a good chunking mechanism.

Alternately, @fabxc came up with this brilliant idea of aligning the offsets to 8/16bytes and that would mean we just store the multiple of 8/16 bytes, giving us upto 64GB of addressable space.

**Comment by shubheksha** [comment]
I'll pick this one up!
