### ISSUE TITLE
Bulk Imports

### ISSUE THREAD

**Issue by gouthamve** [prometheus/tsdb#24]
Implement bulk imports for prefilling. 

Ref: https://github.com/prometheus/prometheus/issues/535

**Comment by codesome** [comment]
I would like to claim this issue. First step to this would be addressing https://github.com/prometheus/tsdb/issues/90, and I am on it now.

**Comment by gouthamve** [comment]
Can be closed via https://github.com/prometheus/tsdb/pull/370
