### ISSUE TITLE
Refactor `serializedStringTuples` used in the index

### ISSUE THREAD

**Issue by shubheksha** [prometheus/tsdb#241]
Refactor the type along with its methods. Make them more readable, rename variables currently, it's confusing. https://github.com/prometheus/tsdb/blob/master/index/index.go#L929-L933

**Comment by shubheksha** [comment]
I'm picking this up.

**Comment by krasi-georgiev** [comment]
that would be really useful, Thanks!
looking forward to the PR.

**Comment by knrt10** [comment]
@shubheksha if you are not working I would like to work on this issue.

**Comment by shubheksha** [comment]
@knrt10 go ahead!
