### ISSUE TITLE
CLI: containerize build of CLI executable

### ISSUE THREAD

**Issue by remeika** [prometheus/tsdb#242]
The tsdb cli has some go 1.9 dependencies; it would be nice to have an option in the makefile to build it without any local dependencies.

**Comment by krasi-georgiev** [comment]
@Gouthamve this seems abandoned so can close and reopen if needed?

**Comment by Gouthamve** [comment]
Yep, the current CLI is not going to be used for anything beyond development for now. When we have proper user-facing use-cases, we will probably revisit this.
