### ISSUE TITLE
Add metric for the space taken of the symbol tables

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/tsdb#244]
If a user has way too many label values this could get large, so having a metric indicating the space taken would be useful.

**Comment by Gouthamve** [comment]
Should this be a prometheus metric or should it be part of the tsdb/promtool cli?

**Comment by brian-brazil** [comment]
A metric of the TSDB itself, as Prometheus has no knowledge of this.

**Comment by sipian** [comment]
If there is no one working on this, I would like to take this issue up.

**Comment by sipian** [comment]
In index/index.go there is a function,  `func (r *Reader) SymbolTable() map[uint32]string`

Based on my understanding, to get the symbol table size we are supposed to call this function and get the total size of the `map[uint32]string`. For map total size, I found [this](https://stackoverflow.com/a/31855111/5730790) reference

Is this the correct direction in solving this issue?

**Comment by brian-brazil** [comment]
Either in-memory or disk works, they're both basically the same size.
