### ISSUE TITLE
Label Values composite index

### ISSUE THREAD

**Issue by gouthamve** [prometheus/tsdb#26]
I see from [this](https://docs.google.com/document/d/13uK6HoEXzX67DuWsJ2PKo8zjpqlgpQ0SIHz2nvMa7f0/edit#heading=h.zzd5egnpdp5) doc that we are going to have composite indexes. But it is still un-implemented. 

@fabxc I am assuming this is a TODO item and you have not dropped the idea of a composite index.

**Comment by fabxc** [comment]
Yes, this is a to-do that should be possible to add seemlessly at a later
point. The label value index interface shows support for it already.

It is useful for advanced autocompletion in Prometheus. For example, if we
want to suggest values for a certain label, it makes sense to only suggest
those that exist for the given metric name (__name__ label). The composite
index provides the required lookup.

**Comment by codesome** [comment]
@krasi-georgiev I was about to implement this in my GSoC. But as there were not many use cases with this, it was decided that we don't implement it for now.

**Comment by krasi-georgiev** [comment]
yeah that is what I wanted to know. 
Autocompletion sounds very useful so really surprising why it didn't get more interest.

**Comment by gouthamve** [comment]
Yes. Also @codesome has a branch somewhere that does this, I think (:
