### ISSUE TITLE
Missing chunks on opening DB

### ISSUE THREAD

**Issue by dim** [prometheus/tsdb#263]
We have embedded tsdb in one our apps. After restarting, we tend do see a lot of these:

```
open /var/lib/myapp/01C4ESEHXCBCW59JXHMP91HBK4/chunks: no such file or directory
open block /var/lib/myapp/01C4ESEHXCBCW59JXHMP91HBK4

github.com/bsm/myapp/vendor/github.com/prometheus/tsdb.(*DB).reload
  $GOPATH/src/github.com/bsm/myapp/vendor/github.com/prometheus/tsdb/db.go:488
github.com/bsm/myapp/vendor/github.com/prometheus/tsdb.Open
  $GOPATH/src/github.com/bsm/myapp/vendor/github.com/prometheus/tsdb/db.go:220
github.com/bsm/myapp.(*store).openDB
  $GOPATH/src/github.com/bsm/myapp/store.go:56
...
```

I have looked through the code but I am not able to pinpoint the issue. Do you have any idea why some blocks have a `chunks` dir and others don't?

**Comment by Gouthamve** [comment]
Hi, are you running NFS or some other networked filesystem? We delete the whole directory at one: https://github.com/prometheus/tsdb/blob/master/db.go#L514-L516 and hence it should not be possible for the directory to exist but not the chunks.

**Comment by dim** [comment]
@Gouthamve sorry, I think I have found the issue on our end. My apologies.

**Comment by antonio** [comment]
@dim would you mind sharing what the problem was? I'm also seeing this problem so maybe you can point me in the right direction. Thanks!

**Comment by dim** [comment]
@antonio sorry, that was too long ago and I simply cannot remember. in the end, we switched away from tsdb to a different solution because of other issues
