### ISSUE TITLE
Add a method for getting all label names

### ISSUE THREAD

**Issue by shubheksha** [prometheus/tsdb#279]
This has to be implemented in the Querier, like https://github.com/prometheus/tsdb/blob/master/querier.go#L34-L35.  
It's needed to implement https://github.com/prometheus/prometheus/issues/2038.

**Comment by Gouthamve** [comment]
We have the info in `reader.labels` map. We can just check for the separator and if there is none, add it to the list.

**Comment by sipian** [comment]
Is there anyone working on this issue? If not I would like to take this up.
