### ISSUE TITLE
Add SelectPostings method to IndexReader

### ISSUE THREAD

**Issue by Gouthamve** [prometheus/tsdb#29]
I think we should a method to IndexReader that is of the form: 
```
SelectPostings(...labels.Matcher) Postings
```
Right now, we have the same functionality being implemented by the querier here: https://github.com/fabxc/tsdb/blob/master/querier.go#L125-L139

**Why?**
Indexing makes more sense for this compared to the querier. We will be probably able to use the internal data structures better instead of having to stick the interface.

Also, are instantiating a new Querier everytime, if we want to add optimisations, such as caching, adding them into the index makes more sense.

**Challenges**
Because of the iterator pattern, we are lazy evaluating the "absent" metrics. But luckily, Postings is also an iterator hence we can bring in the lazy evaluations here also.

**Comment by fabxc** [comment]
The boundary between IndexReader and Querier is obviously a moving target. The question is how close to the actual storage format they should be. So far the philosophy was to stay close and don't add more abstraction on top.

In particular, this method touches to different areas of our index, which is rather high-level.

How in particular would you leverage being close to the underlying data to make things more efficient?
Caches are obviously something to consider at some point. I feel like we don't have a good understanding yet where time is being spent, i.e. whether this area will ever be worth the effort.

**Comment by Gouthamve** [comment]
Hmm, about using the closeness to make it faster, I was thinking about points like 
Intersect is done internally and you need not load **all** the postings out, but I now realise that this point is moot after I implemented iterator on bytes.

But one advantage we will get is the removal of ugly `absent` field. By moving this into IndexReader, we will return a simple postings list that the querier can consume.

Apart from that I agree that any optimisations here needed to be benchmarked to see if they are actually needed.

**Comment by fabxc** [comment]
Mh, how will we get rid of the absent field? I agree that it's a code smell but it would just move somewhere else, no?

**Comment by Gouthamve** [comment]
Hmm, yes, I agree it does have to move somewhere and I was thinking we could move it to a wrapped struct that implements Postings. It would make the querier simpler but the index complex.

It is finally your call and I don't have a strong opinion on this, it just feels cleaner that the index has such a method. Its completely okay to stick to the current interface.

**Comment by Gouthamve** [comment]
So, I am now implementing deletes and have duplicated the select-code again, the first time for the LastValue fast-path: https://github.com/prometheus/tsdb/pull/34/files#diff-e7066179d64e8fef87e1d06dc4a44a2cR145 

For `Delete` and `LastValue` I need the postings so that I can perform custom functions on them. The selection is also not trivial and can be the path for several optimisations down the line. I am now pretty convinced that the selection should potentially live inside `IndexReader` and would like to know your thoughts. @fabxc

**Comment by fabxc** [comment]
As it is a function that can be implemented purely with the exported methods of the IndexReader interface, anything blocking having a function `selectPostings(IndexReader, ...)` or a `postingsReader` type as in your file above? That can be easily shared across usages.

**Comment by Gouthamve** [comment]
Closed via #78 Also absent is not moved inside the postings iterator as it requires looking up the labels which is time-intensive and should not be done twice.
