### ISSUE TITLE
compact/write: Don't write down empty blocks (?)

### ISSUE THREAD

**Issue by bwplotka** [prometheus/tsdb#309]
I had no samples for a while in my Prometheus (because of wrong scraping configuration?). TSDB dumped empty block into my disk which looks like this:
```
01C6XA7C2K2EJKV6GGWQCGNYTC/
-- index (39.53 KB)
-- meta.json (408 B)
-- chunks/
     < empty dir >
```
Meta file:
```
{
    "version": 1,
    "ulid": "01C6XA7C2K2EJKV6GGWQCGNYTC",
    "minTime": 1519236000000,
    "maxTime": 1519243200000,
    "stats": {},
    "compaction": {
        "level": 1,
        "sources": [
            "01C6XA7C2K2EJKV6GGWQCGNYTC"
        ]
    },
}
```
This causes some tiny problems in [Thanos](https://github.com/improbable-eng/thanos) that we need to workaround, but my main questions are:
1) Have you seen that before? How often can that happen?
2) **Is that necessary to produce those?**

In my personal opinion, it can cause lot's of unnecessary compactions (and downsampling for Thanos) and index lookups. It gets even worse for Thanos or other long storage solutions, because these lookups & compactions are bit more expensive. 

Do you think we can just don't write empty blocks down?

The only negative consequence I can think of is the inability to tell from the storage perspective (looking on the blocks) if the Prom/TSDB was down or just Prometheus did not scrape anything (no samples in TSDB).

**Comment by gouthamve** [comment]
Even I think that writing empty blocks can be removed.

See: https://github.com/prometheus/tsdb/pull/245
