### ISSUE TITLE
Downsampling, a la Thanos

### ISSUE THREAD

**Issue by gouthamve** [prometheus/tsdb#313]
The downsampling in Thanos is really interesting: https://youtu.be/l8syWgJ98sk?t=1392

@fabxc Do you think it makes sense to upstream this and also make Prometheus use this?

/cc @brian-brazil

**Comment by gouthamve** [comment]
Hmm, but reduction in CPU and query time improvements? At what scale do you think the benefits start to show?

**Comment by SuperQ** [comment]
I feel like it would be useful to have downsampling in the tsdb directly.  But I also agree with @fabxc that it's a little soon for this integration.

**Comment by fabxc** [comment]
Benefits start to show once your retention becomes so long that you'd
rather consider it long-term storage. In which case Prometheus itself is
not the answer.

**Comment by brian-brazil** [comment]
I agree with @fabxc that this doesn't make sense for Prometheus and thus the TSDB.

**Comment by AlekSi** [comment]
Duplicate of #56.

**Comment by krasi-georgiev** [comment]
Seems we can close this for now? 
@Gouthamve

**Comment by fabxc** [comment]
I'd propose closing this. There are different ways to approach downsampling – none of them is universally better than others. I see no way for providing a canonical solution here.

**Comment by gouthamve** [comment]
Agreed.

**Comment by dmitriy-lukyanchikov** [comment]
Hello guys.
@gouthamve @brian-brazil does it make sence to implement optional downsampling to Prometheus? We experience some issues with Thanos, and we want to implement downsampling to Prometheus itself?
