### ISSUE TITLE
CI integration

### ISSUE THREAD

**Issue by Gouthamve** [prometheus/tsdb#33]
I plan to work on tests most of next week. Should I help setup Travis while at it?

**Comment by fabxc** [comment]
Definitely. I just activated it.

**Comment by fabxc** [comment]
Unfortunately the tests depend on packages from prometheus dev-2.0 branch, which Travis typically cannot pull.
I don't want to really add vendoring to this repository. Maybe best to just port the pkg/textparse and pkg/labels to prometheus master already.

**Comment by Gouthamve** [comment]
Fixed in #55
