### ISSUE TITLE
Change WAL aging method

### ISSUE THREAD

**Issue by SuperQ** [prometheus/tsdb#333]
The current WAL compaction interval happens based on [epoch time](https://github.com/prometheus/tsdb/blob/master/db.go#L809-L812).  This causes all Prometheus servers to write out blocks synchronized at the same time.

For large clusters, this can cause a thundering herd of IO, especially with something like Thanos writing to a bucket storage.

It would be better to track the age of the WAL, and "age out" after the desired interval.

**Comment by beorn7** [comment]
On the other hand, the aligned block boundaries are extremely handy when  stitching together blocks from different servers. I'm using this regularly (and I assume it was @fabxc 's original motivation to align the block boundaries).

**Comment by brian-brazil** [comment]
Yes, we decided to trade simplicity against simultaneous load increases on different servers.

**Comment by fabxc** [comment]
@SuperQ is this a theoretical concern or did you run into any issues in production? What we know so far, IO to write out initial blocks is very small.
I suppose Thanos could jitter its uploads quite a bit – it's not latency sensitive at all in that regard.

**Comment by krasi-georgiev** [comment]
I don't quite understand this , looking the at code there is no compaction for the WAL. 
@SuperQ did you mean block compaction?

**Comment by SuperQ** [comment]
@fabxc Theoretical concern at this point.  It should be minimal, but I like to avoid these kinds of distributed systems issues where possible.

@brian-brazil Based on what @juliusv said, merging blocks like that would be fragile, as a small time skew between two servers would cause block overlap, which is supposedly not good for the TSDB.

**Comment by SuperQ** [comment]
Part of why I would like this is to simplify the 1.x local storage to TSDB migration.  By aligning the TSDB wal with start time of the server, rather than epoch, I can do a more clean background upgrade by doing this procedure:

* Shutdown Prom v1
* Startup Prom v2 with clean data dir
* Background run the storage migrator
* Shutdown Prom v2
* Move migrated blocks into place
* Restart Prom v2

**Comment by SuperQ** [comment]
I'm not strongly opinionated here. Feel free to close.

**Comment by krasi-georgiev** [comment]
Ok let's close and will revisit if needed.
