### ISSUE TITLE
Support file locking for Windows

### ISSUE THREAD

**Issue by fabxc** [prometheus/tsdb#338]
The current file locking implementation is effectively a noop on Windows.

**Comment by krasi-georgiev** [comment]
just tried it on windows and starting a second Prometheus with the same DB returns an error so locking is working as expected. 
Also looked at the code and it is indeed implemented for windows as well.
https://github.com/prometheus/tsdb/blob/109252f3aa66b954d237978b5fac7a4e57edf4da/fileutil/flock_windows.go#L26-L36


@fabxc 	please let me know if you meant something else.
