### ISSUE TITLE
remove the initAppender and just use the head appender with some initiallizator

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/tsdb#360]
the `initAppender` seem unnecessary step when all we need is `a.head.initTime(t)` at the first `appender.Add()` which should be able to implement directly in the head appender with some bool - `isInitialized` or similar.

**Comment by fabxc** [comment]
That is trading of a single check when instantiating the appender for thousands of checks for every single sample.
Most likely it won't matter at all (branch prediction or negligible cost in general). But performance should be verified regardless.

**Comment by krasi-georgiev** [comment]
thanks for the feedback
wouldn't we  still have a  single `if` in both cases?
`if a.app != nil {...`
vs
`if initilized == false {...`

**Comment by krasi-georgiev** [comment]
just tried it, but it creates races and can't make the creation of the appender atomic.
