### ISSUE TITLE
draft comparison of tsdb vs clickhouse

### ISSUE THREAD

**Issue by vtolstov** [prometheus/tsdb#362]
Hi! I need to store metrics from libvirt vm - cpu,memory,network,disk stats:
* 24 hours - each minute metrics
* 1 month - each hour sum of metrics
* 6 month - each day sum of metrics 

each hardware server have 100-200 vm, each dc have 100 hardware servers (10000-20000 vm in sum)

does it possible to store this metrics in tsdb and how to determine size for files?

and can you compare tsdb vs clickhouse in case of storing metrics (i know that clickhouse have query language map/reduce, sharding and so, but in case of prometheus remote storage)?

**Comment by krasi-georgiev** [comment]
Although I would be interested to see some results, this is quite specific to your current project needs so unless you are willing to run these tests and post the results I don't think anyone here would spend the time on this issue.
