### ISSUE TITLE
Setting --storage.tsdb.retention is not working

### ISSUE THREAD

**Issue by lapshin1988** [prometheus/tsdb#368]
Hello!

I tried use `storage.tsdb.retention` (from docs https://prometheus.io/docs/prometheus/latest/storage/) command line option for 2 hours (`--storage.tsdb.retention==2h`). But it is not working. Metrics stored for 15 days. I found source code:
```
st, err := tsdb.Open(dir, l, nil, &tsdb.Options{
		WALFlushInterval:  200 * time.Millisecond,
		RetentionDuration: 15 * 24 * 60 * 60 * 1000, // 15 days in milliseconds
		BlockRanges:       tsdb.ExponentialBlockRanges(2*60*60*1000, 5, 3),
	})
```

As I understand `storage.tsdb.retention` is not working for now?

**Comment by gouthamve** [comment]
Hi, thanks for trying it out and digging into the source, I don't think the flag is broken. Maybe try: `--storage.tsdb.retention=2h` (with a single `=`). Also, we pass the correct flag in prometheus, not sure which source you are referring to: https://github.com/prometheus/prometheus/blob/master/storage/tsdb/tsdb.go#L145

**Comment by simonpasquier** [comment]
If you're talking about this code then it is only for the TSDB command line interface, it isn't used by the Prometheus server.

https://github.com/prometheus/tsdb/blob/eeb3a7435a75c065cd5a6c10b02abd4c579e34e8/cmd/tsdb/main.go#L106

AFAICT retention is working on Prometheus v2.3.2. Can you provide more details?

**Comment by lapshin1988** [comment]
Hi! Sorry, I use `storage.tsdb.retention=2h`. Metrics collected for 4 hours. Prometheus ran in docker container and the server placed in Germany/Berlin (+2 hours). Maybe I must add some settings?

**Comment by krasi-georgiev** [comment]
@lapshin1988 if you think the issue is resolved please close the ticket. Thanks
