### ISSUE TITLE
[Q] SeriesIterator.Seek definition fuzzy

### ISSUE THREAD

**Issue by Gouthamve** [prometheus/tsdb#37]
So I am working on tests and I am not sure if the behaviour is right for [`SeriesIterator.Seek`](https://github.com/prometheus/tsdb/blob/master/querier.go#L468-L471). There are 2 variables (`ts`, `tt`) in the comment and I am assuming both are the same.

According to the definition, if there is a chunk with values at `1, 2, 4, 5`, `Seek(3)` should return the value at `2`, no? I am seeing that we return the [value at `4`](https://github.com/prometheus/tsdb/blob/master/querier.go#L584-L586).

**Comment by Gouthamve** [comment]
Looking at [how PromQL uses](https://github.com/prometheus/prometheus/blob/dev-2.0/storage/buffer.go#L37-L38) it shows that we are indeed `Seek`ing to first value after `t`. And to get the last value before `t`, we later do a [`PeekBack()`](https://github.com/prometheus/prometheus/blob/dev-2.0/promql/engine.go#L732).

**Comment by fabxc** [comment]
Our iterators are generally forward-streaming only. If the documentation should be clearer, changes are certainly valid.

The assumption is generally that TS values are collected and accessed in order. It certainly one that allows the storage to perform well. The compression algorithm is also based on this assumption and other efficient ones would certainly be as well.

Any sort of peek back of one or more values can be implemented with a buffer.

**Comment by Gouthamve** [comment]
Fixed in #36
