### ISSUE TITLE
Incorrect NumTombstones after block.Delete(...)

### ISSUE THREAD

**Issue by codesome** [prometheus/tsdb#384]
Found this while working on https://github.com/prometheus/tsdb/pull/374

Apparently updating `NumTombstones` only [here](https://github.com/prometheus/tsdb/blob/a8966cb53d39747c5d7b7ba787873b52899881d0/block.go#L487) is incorrect. For example, if currently there were no stones and we want to add new stones in `Delete(...)`, `NumTombstones` is nowhere updated.

Please correct me if I am wrong. I will open a PR for this soon.

**Comment by gouthamve** [comment]
Yes you are right. This was introduced in this: https://github.com/prometheus/tsdb/pull/212

Please fix it and add a test for the same :)
