### ISSUE TITLE
Missing unit on lowest timestamp metric.

### ISSUE THREAD

**Issue by SuperQ** [prometheus/tsdb#395]
In https://github.com/prometheus/tsdb/pull/363 a new metric, `prometheus_tsdb_lowest_timestamp`, was added.

It seems like this is milliseconds, but is missing the unit.

Maybe we should convert this to seconds and make it `prometheus_tsdb_lowest_timestamp_seconds`.

**Comment by simonpasquier** [comment]
See https://github.com/prometheus/tsdb/pull/363#discussion_r204637082 for the rationale. We have the same situation with the `prometheus_tsdb_head_max_time` and `prometheus_tsdb_head_min_time` metrics.

**Comment by SuperQ** [comment]
I don't think that rationale makes sense. If it's a timestamp, it has to have a unit, which we should know by the datatype.

**Comment by brian-brazil** [comment]
The unit is defined by the code that uses it though, not the tsdb. To the TSDB this is just a number.

**Comment by SuperQ** [comment]
Maybe the TSDB shouldn't expose this metric, but we have Prometheus create the metric instead so we have an opinion on what the type is.

**Comment by krasi-georgiev** [comment]
What are we doing with this one?
