### ISSUE TITLE
Implement backups

### ISSUE THREAD

**Issue by fabxc** [prometheus/tsdb#4]
Our design generally allows easy backups. Necessary steps for this are:

1. Disable compactor temporarily
2. Create a backup directory that hard-links to all existing block files
3. Snapshot() method that allows compacting current in-memory blocks into fully persistent blocks (not strictly necessary but nicer than backing up write-ahead log segments)
4. Re-enable compactor so we don't ramp up memory during 5. – because all compaction actions replace old files rather than modifying, the inodes the hard links point to remain valid
5. An external tool, e.g. rsync, can copy the backup directory somewhere safely and delete the directory

To disable/enable the compactor and trigger snapshots we can simply rely on the using application to make the method accessible or provide an optional convenience HTTP server in the tsdb directly.

**Comment by Gouthamve** [comment]
Closed via #88
