### ISSUE TITLE
Collisions are likely in headAppender.Add's ref logic

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/tsdb#41]
https://github.com/prometheus/tsdb/blob/778103b45060697e8452f3d00a6e8fe1f11306da/head.go#L308

headAppender.Add uses a 31bit random number to generate refs. A collision is likely at about 64k new series from a target/rule, which is almost certainly going to happen.

An approach such as a central counter would be safer, though 31 bits still feels a tad small.

**Comment by fabxc** [comment]
Yes, this should be fixed before the next alpha. A counter within the transaction and a signaling bit for clients to not store the ref beyond the transaction would be one approach.

That means that all clients that want to use `AddFast` have to maintain two separate caches – for within the current transaction and one for beyond. As it is, after the transaction initially creating a series, the next transaction has to to a regular `Add` for the same series regardless.
Given that Prometheus itself does not currently append multiple samples for the same series in a transaction, I wonder if it is worth it at this point.

Even easier would be to reserve the 0 or max ID for "not found" and just always return it if a series was newly created.

**Comment by brian-brazil** [comment]
How bad is it just to do the `Add` every time?

**Comment by fabxc** [comment]
Every time as in never do the `AddFast`? It's one of the major reason for saving CPU aside from series maintenance. Without it, about 80% of CPU cycles are spent on allocating/GCing byte slices and hashing them.

**Comment by Gouthamve** [comment]
This can be closed.
