### ISSUE TITLE
blockQuerier returns data outside the time-range

### ISSUE THREAD

**Issue by Gouthamve** [prometheus/tsdb#43]
I was writing tests for blockQuerier and realised that it doesn't check the returned values to be inside `(mint, maxt)`.

So blockQuerier returns all the values from a chunk if a chunk is partially inside `(mint, maxt)`. This is because [`blockSeriesSet`](https://github.com/prometheus/tsdb/blob/master/querier.go#L158-L169) has no info about `(mint, maxt)` and [`populatedChunkSeries` returns all `chunks` partially inside the time-range](https://github.com/prometheus/tsdb/blob/master/querier.go#L413-L434). It doesn't remove the values outside `(mint, maxt)`.

**Comment by Gouthamve** [comment]
Fixing this would mean adding `mint, maxt` to SeriesIterators, namely `chunkSeriesIterator` and `chainedSeriesIterator`. If you are okay with that, I will go ahead and fix this.

**Comment by fabxc** [comment]
Yep, that's an oversight. Wondering whether it practically matters for PromQL.  
But we should add the bounds checking to implement the API contract properly of course. The overhead is probably not significant compared to PromQL itself.
