### ISSUE TITLE
What's the reason to slice before calling PutUint32()

### ISSUE THREAD

**Issue by nilsocket** [prometheus/tsdb#436]
https://github.com/prometheus/tsdb/blob/d804a27062fc524a7494592b72cb23cae1f709cc/chunks/chunks.go#L177
```go
meta[:4] // I think this is unnecessary
```

**Comment by krasi-georgiev** [comment]
I think it is something to do with the compiler slice bound hints.
https://www.ardanlabs.com/blog/2018/04/bounds-check-elimination-in-go.html

btw we keep the github issue for bug reports and PRs.

Please use the irc and mail group for questions.

**Comment by nilsocket** [comment]
But the bounds-check elimination is being done in the library [itself](https://github.com/golang/go/blob/d76b1cdf286551a81fd4c1012cbf8686d344cc32/src/encoding/binary/binary.go#L115).

**Comment by krasi-georgiev** [comment]
Yeah I noticed this as well, maybe @fabxc 	can add some context.
