### ISSUE TITLE
Concurrent map write in (*headAppender).Add()

### ISSUE THREAD

**Issue by mattbostock** [prometheus/tsdb#44]
I'm seeing a panic due to concurrent map writes in: `(*headAppender).Add()`:
https://github.com/prometheus/tsdb/blob/25d45465189ea9b7f2c894188c06d1853bfa79ba/head.go#L322-L323

Is the intention that the caller to `Add()` should implement their own locking? Is there a reason that `Add()` shouldn't manage a mutex itself?

Is this is a documentation issue, happy to raise a PR add a comment to clarify.

**Comment by Gouthamve** [comment]
Wait. `Add()` being called concurrently? Can you post the stack-trace? Operations on Appender are supposed to be serialised as I documented it here: https://github.com/prometheus/tsdb/pull/28/files#diff-7a117cbfd5485ed35efcbb2995c37aa0R63

If `Add()` is being called concurrently, then it is a bug. Is it happening in Prometheus or are you using tsdb as a library?

That PR is highly unlikely to get in so a PR for the comment would be great.

**Comment by mattbostock** [comment]
I'm using tsdb as a library.

Is the thinking that the caller of `Add()` (e.g. Prometheus) will be doing locking at a different scope, and so it doesn't make sense to add additional locking here?

Will raise a PR to add a comment - thanks!

**Comment by mattbostock** [comment]
I see now that the Appender should not be reused after committing the samples, so in my case I don't need concurrent access. Closing this issue.
