### ISSUE TITLE
Ability to create db with NopWAL

### ISSUE THREAD

**Issue by gouthamve** [prometheus/tsdb#452]
We create a test db in prometheus for unit-testing and general tests. Ideally we never write anything to disk there but turns out we do because we cannot disable the WAL.

**Comment by krasi-georgiev** [comment]
Why is writing to disk a problem?

**Comment by krasi-georgiev** [comment]
ping @gouthamve

**Comment by gouthamve** [comment]
Well, it is not much of a problem, but I wouldn't expect my alert-testing tool to write to disk. Little counter intuitive.

**Comment by krasi-georgiev** [comment]
there is already a `WALFlushInterval` option which doesn't seem to be used for anything now so I wonder if we put it use and eventually set a very high value for tests would solve the problem without api changes.

https://github.com/prometheus/tsdb/blob/d50b9a5619b2efb7559ea1a7187df9fa5c209121/db.go#L56

**Comment by krasi-georgiev** [comment]
I looked into this again and it seems that @fabxc 	removed the wal interface to save some lookup time of the interface indirectio. instead all head functioned return early when the `wal` is `nil`. so instead of implementing a noop wal can just pass `nil` for the `wal` and this does the same job.

**Comment by vn-ki** [comment]
> so instead of implementing a noop wal can just pass nil for the wal and this does the same job.

Does this mean nothing has to be done here?

If no, I would like to take up this issue. Can you please explain what has to be done?

**Comment by krasi-georgiev** [comment]
waiting for @gouthamve's input.

**Comment by norbertwnuk** [comment]
I see additional scenario where such feature would be useful: Prometheus HA installation does not that much need WAL on disk when the data are federated via remote write interface / directly from the short duration blocks (Thanos).

**Comment by bwplotka** [comment]
^ soon remote write will use WAL, so it's not the case anymore.

@gouthamve can we provide some accept criteria for this?

I guess it's "do not produce any files" in unit test when we don't test it?

**Comment by krasi-georgiev** [comment]
please note my comment from earlyer:

> I looked into this again and it seems that @fabxc removed the wal interface to save some lookup time of the interface indirection. instead all head functions return early when the wal struct is nil. so instead of implementing a noop wal can just pass nil for the wal and this does the same job.

**Comment by bwplotka** [comment]
Yep if that works then cool, let's improve our tests with that where WAL is not needed 👌

**Comment by gouthamve** [comment]
This is perfect. I think the only thing left now is to make an option for `DB` so that it passes a `nil` wal to `NewHead()`.
