### ISSUE TITLE
Document that labels must be sorted before passing to (*headAppender).Add()

### ISSUE THREAD

**Issue by mattbostock** [prometheus/tsdb#47]
It seems that labels must be sorted before passing them to `(*headAppender).Add()`, otherwise the labelsets will be considered distinct.

We should either ensure the labels are sorted (if the overhead is not significant) or document that the labels must be sorted.

**Comment by Gouthamve** [comment]
Umm duplicate of #32?

**Comment by mattbostock** [comment]
My bad, I should have checked for existing issues. Closing, thanks.
