### ISSUE TITLE
Add format documentation (binary layout of index/chunks)

### ISSUE THREAD

**Issue by telendt** [prometheus/tsdb#49]
I've just read [Fabian's blogpost](https://fabxc.org/blog/2017-04-10-writing-a-tsdb/) which gives high level introduction to new V3 storage. I'd like to get more familiar with the binary layout of  index/chunks but I'm not sure where to look (should I dive deep into source code?). Are there some documents around that describe it and if so, can you link then in the README?

**Comment by fabxc** [comment]
I plan to document the format while giving it another pass here and there – hopefully by end of month. Will update here.

**Comment by Gouthamve** [comment]
@fabxc I think this can be closed.
