### ISSUE TITLE
Snapshots with head block are unsafe

### ISSUE THREAD

**Issue by gouthamve** [prometheus/tsdb#518]
Initial review of https://github.com/prometheus/tsdb/pull/514/ made me realise how snapshots can produce chunks of arbitrary bytes if head block is included.

When we write out the headblock here: https://github.com/prometheus/tsdb/blob/master/db.go#L883, we use the `Chunks` inside head here: https://github.com/prometheus/tsdb/blob/master/compact.go#L655

The chunks returned are [`safeChunk`](https://github.com/prometheus/tsdb/blob/master/head.go#L1020-L1024)s that are safe for iteration but not for [writing out](https://github.com/prometheus/tsdb/blob/master/compact.go#L689) as the bytes returned would be changing as the chunks are being appended to.

This means that the current headblock snapshots could be completely broken and might even have "wrong" data. 

I don't have a good solution for this now, but should we disable snapshots with `Head` for the time being? @krasi-georgiev @bwplotka

**Comment by gouthamve** [comment]
When we call snapshot, just cutting a new chunk for every series would fix this imo. That is the most performant way I can think of.

Another way would be re-write open chunks on Snapshot which would mean millions of chunks to be re-written, just not sure how bad it will be allocation and CPU wise. Needs to be benchmarked.

**Comment by bwplotka** [comment]
Yup, wonder what would be performance of that rewrite of open chunks.

**Comment by bwplotka** [comment]
But disabling sounds bad as well, wonder how it worked before chunk boundary check? I guess it worked fine with race right? (:

**Comment by gouthamve** [comment]
I might be being too pedantic, but I would think it "never" worked. The snapshots could literally be persisting a wrong sample and we would never know it.

**Comment by bwplotka** [comment]
Agree.

I really think iterating over open chunks won't be that bad. And we don't need super fast snapshots withHead (:

**Comment by bboreham** [comment]
Is this similar to the problem I found at https://github.com/cortexproject/cortex/pull/1221#issuecomment-462499977 - marshalling doesn't save enough info to be able to add to the chunk afterwards ?

(PS: when creating a Github link to code, you can press the `y` key to get a specific commit rather than `master`, so that people who follow the link later will know which line you meant)

**Comment by krasi-georgiev** [comment]
sounds different, 
this one is getting the raw bytes (Chunk.Bytes()) from the last chunk while being appended to.
