### ISSUE TITLE
Support selectors for LabelNames and LabelValues

### ISSUE THREAD

**Issue by codesome** [prometheus/tsdb#530]
Regarding https://github.com/prometheus/prometheus/issues/5248

The best way now is equivalent to querying the tsdb for series and filter the required information - which is inefficient.

**Comment by brian-brazil** [comment]
That's the only way to do it and the most efficient, I don't see the need to extend the API.

**Comment by krasi-georgiev** [comment]
Original issue closed so no need to keep this one open
