### ISSUE TITLE
double metric

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/tsdb#545]
prometheus_tsdb_lowest_timestamp_seconds
prometheus_tsdb_lowest_timestamp (unit: ms??)

I think that we could delete the second one.

**Comment by roidelapluie** [comment]
my understanding is that the second one is coming from TSDB whic is unit agnostic and could be "unregistered" by prometheus when the first one is registered.

**Comment by brian-brazil** [comment]
Yes, that's what's happening. They're both meant to be present.

**Comment by roidelapluie** [comment]
Should we unregister the first one?

Or maybe pass a parameter "unit" to TSDB so that it can expose directly the correct metric?

Otherwise I will close this.

**Comment by brian-brazil** [comment]
No, what the tsdb exports is a black box to Prometheus.
