### ISSUE TITLE
Compaction with downsampling

### ISSUE THREAD

**Issue by drscre** [prometheus/tsdb#56]
Prometheus currently has no downsampling support. It can be achived via federation, but it's way too messy.

Maybe now it is possible to integrate downsampling support into compaction process?

Another usefull feature would be to have different ttl for different metrics.
For example in our setup, a lot of metrics are aggregated via recording rules, and after "recording" they are never queried again.

**Comment by fabxc** [comment]
The new storage certainly makes it easy to add such things to the compaction process. Same with dynamic retention policies. Both have been thought about and are somewhat semi-planned either as a core feature or potentially by an external process.

On requirement for downsampling to work properly is staleness handling, which we luckily started working on just recently.

**Comment by anarcat** [comment]
i heard there was progress about downsampling on the master branch ... can anyone clarify what the current state of affairs is here?

**Comment by krasi-georgiev** [comment]
closing in favour of the more recent discussion in  #313
