### ISSUE TITLE
Improve renameFile function

### ISSUE THREAD

**Issue by zhulongcheng** [prometheus/tsdb#564]
https://github.com/prometheus/tsdb/blob/3ab5f4e57902eea758f1940dd852e954b5d5ba6b/compact.go#L1015-L1034

If `to` is removed successfully but failed to rename `from` to `to`,  data in `to` will be lost.

---

Maybe something like this:
1. rename `to` to `to.rename.tmp`
2. rename `from` to `to`
3. remove`to.rename.tmp`

**Comment by zhulongcheng** [comment]
cc @krasi-georgiev

**Comment by krasi-georgiev** [comment]
I quickly checked and it seems that the way `renameFile` is used this shouldn't cause any issue. 
do you see any parts where `renameFile` is used in a way to cause data loss in case of an error as you have described it?

**Comment by zhulongcheng** [comment]
Ex: [OpenBlock](https://github.com/prometheus/tsdb/blob/master/block.go#L280-L334) -> [writeMetaFile](https://github.com/prometheus/tsdb/blob/master/block.go#L233-L258) -> [renameFile](https://github.com/prometheus/tsdb/blob/master/compact.go#L1015-L1034)

The `meta.json` file is removed.
```
drwxr-xr-x  6 logan  staff   192B Mar 26 11:53 ./
drwx------  3 logan  staff    96B Mar 26 11:53 ../
drwxr-xr-x  3 logan  staff    96B Mar 26 11:53 chunks/
-rw-r--r--  1 logan  staff   315B Mar 26 11:53 index
-rw-r--r--  1 logan  staff   264B Mar 26 11:53 meta.json.tmp
-rw-r--r--  1 logan  staff     9B Mar 26 11:53 tombstones
```

**Comment by krasi-georgiev** [comment]
Thanks. 

Seems that https://github.com/prometheus/tsdb/issues/565 is related so can you join both issues into one and close this one.

**Comment by zhulongcheng** [comment]
Merge into #565
