### ISSUE TITLE
Cleanup temp file if rename/replace failed

### ISSUE THREAD

**Issue by zhulongcheng** [prometheus/tsdb#565]
https://github.com/prometheus/tsdb/blob/3ab5f4e57902eea758f1940dd852e954b5d5ba6b/compact.go#L1015-L1034

If `to` is removed successfully but failed to rename `from` to `to`,  data in `to` will be lost.

Ex: [OpenBlock](https://github.com/prometheus/tsdb/blob/master/block.go#L280-L334) -> [writeMetaFile](https://github.com/prometheus/tsdb/blob/master/block.go#L233-L258) (re-create a meta file) -> [renameFile](https://github.com/prometheus/tsdb/blob/master/compact.go#L1015-L1034)

The `meta.json` file is removed.
```
drwxr-xr-x  6 logan  staff   192B Mar 26 11:53 ./
drwx------  3 logan  staff    96B Mar 26 11:53 ../
drwxr-xr-x  3 logan  staff    96B Mar 26 11:53 chunks/
-rw-r--r--  1 logan  staff   315B Mar 26 11:53 index
-rw-r--r--  1 logan  staff   264B Mar 26 11:53 meta.json.tmp
-rw-r--r--  1 logan  staff     9B Mar 26 11:53 tombstones
```

---
The callers of [renameFile](https://github.com/prometheus/tsdb/blob/3ab5f4e57902eea758f1940dd852e954b5d5ba6b/compact.go#L1015-L1034) should check and cleanup temp file if `renameFile` return an error.

https://github.com/prometheus/tsdb/blob/3ab5f4e57902eea758f1940dd852e954b5d5ba6b/block.go#L233-L258

---

TODO:
- [ ] a safer way to replace files.
- [ ] remove the temp file.

**Comment by krasi-georgiev** [comment]
yes this is a bug.

Feel free to open a PR as described in  https://github.com/prometheus/tsdb/issues/564 or just handle the tmp deletion in the caller.
