### ISSUE TITLE
Change chunk file format

### ISSUE THREAD

**Issue by fabxc** [prometheus/tsdb#58]
Currently we write lists of chunk to a chunk file. Each chunk starts with a flag for its used compression. A CRC32 checksum over all chunks of an inserted is written at the end. I'm currently pondering with a few things:

* Have one checksum per chunk. The 4 byte overhead is likely fine and the checksum applies some sort of artificial grouping over an otherwise independent pool of chunks. That we add chunks in batches for the same series is just an optimisation so they are co-located but no requirement in any way. This seems generally to make sense as the space requirements are irrelevant.
* Move the checksum into the index. More contentious, we could not verify chunks without the index anymore.
* Move even the chunk compression flag into the index as well. Even more contentious.
* The next step would even be to hold the chunk length in the index as well. At this point chunk files really just become a binary blob container.

I for the last three points there's no clearly right way to do it. So just interested in opinions.

**Comment by grobie** [comment]
I'm totally in favor of adding checksums to every chunk. I recently read some papers on data corruption and was surprised to see how likely bit errors can occur. I found some interesting approaches to test a database's corruption handling and robustness and have the goal to add such tests to tsdb.

Moving the checksums into the index doesn't sound like a good idea. They should be stored as closely to the actual data as possible (in terms of sector/page locality). If we lose the index file, or have a corrupted index file, we'd be longer able to verify whether additional data corruption has occurred in the actual chunks.

I don't have a strong opinion on the last two points. I'd tend to keep all chunk related flags as a header in the beginning of a chunk, but this might need some more thinking on chunk alignment etc.

**Comment by fabxc** [comment]
So I thought some more today:

> Moving the checksums into the index doesn't sound like a good idea. They should be stored as closely to the actual data as possible (in terms of sector/page locality). If we lose the index file, or have a corrupted index file, we'd be longer able to verify whether additional data corruption has occurred in the actual chunks.

If you lose the index data, you don't even know what that binary blob of compressed sample data is part of. From a corruption detection/data recovery perspective it doesn't matter. A point @tom-wilkie brought up is, that you can verify that the chunk an index references is actually the correct one – kind of a nice property in addition (imagine for same reasons chunk files got swapped, some backup copying around files messing up, etc.).

The series section is currently guarded by a single CRC32 – that's an oversight and not the case for the postings list for example.  
One corruption in that section and the entire index is basically invalid. Trivial approach here is calculating a CRC for  each series (label set + chunk metas/refs). That's about 50-120 bytes each. Chunks themselves are in the range of 100-300 bytes. CRC32s for each of those seem "wasteful" as a CRC16 is totally sufficient here. LevelDB for example uses CRC32s per 4KiB block – I don't see a similar approach feasible for us as it makes on-the-fly validation more expensive/complicated.  
Also, CRC32s have amd64 hardware support and are not expensive in the big picture in general (<2% size overhead, a few sample-decompressions worth of computation). Also, the chosen polynomial seems to be well-suited for disk corruption patterns. So overall using as "wasteful" CRC32 seems the best option – we can validate every series and every chunk within individually and minimise unrecoverable data.  

Postings lists and label value indices already are checksummed per item, i.e. losing your value index for the `method` label means you can still read the one for the `job` label. I think that's a reasonable amount of granularity.

A remaining problem is the symbol table. It should generally not be longer than a few tens of kilobytes and is guarded by a CRC32 as well. That's fitting for the data size but if that section corrupts, there's obviously no degraded mode ("we are hiding some broken data") like with a single broken chunk (aside from "that data here is maybe wrong"). Having more granular CRCs doesn't help practically.  
Error correction would be one option but complicates things. One could also just store it twice for fall-back. But I think that's getting quite complicated pretty early. The format is iterable and we could add it later. Practically speaking, one could also re-assemble it from all the postings list or something for recovery.

**Comment by grobie** [comment]
> If you lose the index data, you don't even know what that binary blob of compressed sample data is part of.

My statement was under the assumption that the index file would be somehow recoverable. Thinking about it, that's obviously not true. In that case, I don't have a strong opinion in either direction. The point about being able to validate an index file is used together with the correct chunks sounds reasonable.

From a write pattern (in terms of SSD pages) perspective, it shouldn't really matter either, correct?

**Comment by fabxc** [comment]
> From a write pattern (in terms of SSD pages) perspective, it shouldn't really matter either, correct?

Correct. Just that you need a good bit of additional logic to spread checksums in the correct spacing but not in between relevant entries because than you cannot access them as a standard byte slice anymore without memmoves.

Also CRCing 4k bytes is obviously more expensive than 200. Then you also have to track whether you validated a page just before when accessing another entry in the same page. Seems like a lot of trouble actually.

**Comment by fabxc** [comment]
This is largely complete. Thing I keep wondering is about putting series information itself into each chunk file for disaster recovery as well. That'd probably just be duplicated in the index though and could be added later as another version and be optional as it has overhead.
