### ISSUE TITLE
Log storage filesystem type at startup

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/tsdb#596]
The `statfs` call allows us to determine filesystem type, we could use this to log this at startup which would be useful from a support standpoint. This will only work on Unix.

**Comment by eightlimbed** [comment]
I'l like to call dibs on this issue :)

**Comment by krasi-georgiev** [comment]
go ahead :+1:

**Comment by eightlimbed** [comment]
Hey @brian-brazil, @krasi-georgiev  -- just wanted some clarification. We want to log the file system type when the `prometheus` binary runs, yes? I'm confused because this issue is in the tsdb repo.

**Comment by brian-brazil** [comment]
Yes. The tsdb repo is used by Prometheus, so it's something to log when the
DB is opened.
