### ISSUE TITLE
cpu usage 100%

### ISSUE THREAD

**Issue by qinguoan** [prometheus/tsdb#60]
I scrape 15w samples per second, without rules  cpu usage 40% (v1.5.2 300%).
After I used about 300 rules for aggregation, cpu full used with 20% iowait (nvme device). (machine got a 38 cores cpu, v1.5.2 usage 600% without iowait).

Attached file is pprof result.  
evaluation_interval: 1s

[pprof.prometheus.localhost:9090.samples.cpu.001.pb.gz](https://github.com/prometheus/tsdb/files/955054/pprof.prometheus.localhost.9090.samples.cpu.001.pb.gz)

**Comment by qinguoan** [comment]
cpu iowait high while disk iops is 0.

**Comment by qinguoan** [comment]
I may have found out the reason, in rule's manager all rules are evaluated in parallel, this may make iowait between cpu core switch (not quite sure)?  I just used a NumCPU goroutines to handle manager's Eval() est time is the same as before while cpu usage is OK.

**Comment by fabxc** [comment]
This seems to relate to Prometheus 1.5. Please reopen your issue in prometheus/prometheus should it still be a problem.
