### ISSUE TITLE
How best to write blocks when bulk importing?

### ISSUE THREAD

**Issue by tyrken** [prometheus/tsdb#621]
I'm trying to do bulk importing loads of Whisper files from a Carbon/Graphite server to TSDB, so we can keep history when moving metric systems.  So far I've a rough prototype to do low-scale reads from Whisper & write to blocks, as if they were scrapes.  I.e. if I have metrics "A", "B", and "C", and I have their values at timestamps "1", "2" and "3" (nicely synchronised due to the way Whisper works), then I:

* Make tsdb.Appender
* Write A1, B1, C1
* Commit
* Make tsdb.Appender
* Write A2, B2, C2
* Commit
* Make tsdb.Appender
* Write A3, B3, C3
* Commit

Is this the right pattern?  I get the feeling from some of the talks on Thanos compaction (where I hope to shove the blocks eventually) that interleaving the data isn't so good performance wise, and instead I should do A1, A2, A3, B1, B2, B3, etc. - or is this moot since Thanos will re-write them anyway?

Apologies for the question-as-an-issue, but thanks in advance for any advice on using TSDB or in general on the approach.

**Comment by krasi-georgiev** [comment]
I think this would be the most performant way:
```
app := db.Appender()
for _,labels := range []labels{...}{
	ref,err:= app.Add(labels,t,v)
	// Check error
	app.AddFast(ref, t, v)
}
app.Commit
```

**Comment by krasi-georgiev** [comment]
feel free to reopen if you have anymore questions.

**Comment by tyrken** [comment]
Thanks - working on it...

**Comment by bwplotka** [comment]
Yup, the only decision you need to make is in how many blocks you want data in. If one TSDB block then single appender in same directory. Otherwise, many different directories and then different appenders (TSDB instances) (:

**Comment by bwplotka** [comment]
Just curious how you want import TSDB data (blocks or WAL) to Prometheus/Thanos?

**Comment by krasi-georgiev** [comment]
I think for all cases blocks should work best and let the let the compactor handle the overlaps.
