### ISSUE TITLE
Proposal to compute actual size of files on filesystems with compression

### ISSUE THREAD

**Issue by dipack95** [prometheus/tsdb#657]
We've noticed an issue with prometheus/tsdb unable to realise that it is on a filesystem with compression enabled (ZFS dataset with lz4 compression). When calculating the space remaining for things like the WAL, it uses the logical space occupied by the files on the fs, which is acceptable on regular filesystems, but does not represent the actual size on disk on compressed filesystems.

To get around this, we can use the actual physical size of the files, when on a fs with compression enabled, as shown in the snippet below, which uses the `syscall` package.

```
var st syscall.Stat_t
syscall.Stat(filename, &st)
size := st.Blocks * 512
```
We multiply the number of blocks by 512, as explained in the [manpage for stat(2)](https://www.gnu.org/software/libc/manual/html_node/Attribute-Meanings.html).

A quick benchmark comparing the difference in execution time of the new `syscall.Stat(...)` with the current `FileInfo.Size()`

```
dipack@dpanjabi-debian-vm:/zrfiles/cs$ go test -bench=.
Size of / is 140758873192258
goos: linux
goarch: amd64
BenchmarkGolangSize-4                  1    4485581373 ns/op
Size of / is 28901134336
BenchmarkGolangTrueSize-4              1    4207845697 ns/op
PASS
ok      _/zrfiles/cs    8.698s
dipack@dpanjabi-debian-vm:/zrfiles/cs$ go test -bench=.
Size of / is 140758875275285
goos: linux
goarch: amd64
BenchmarkGolangSize-4                  1    3513830374 ns/op
Size of / is 28928441344
BenchmarkGolangTrueSize-4              1    4411896506 ns/op
PASS
ok      _/zrfiles/cs    7.930s
dipack@dpanjabi-debian-vm:/zrfiles/cs$ go test -bench=.
Size of / is 140758876814687
goos: linux
goarch: amd64
BenchmarkGolangSize-4                  1    3574522671 ns/op
Size of / is 28942242816
BenchmarkGolangTrueSize-4              1    4351363943 ns/op
PASS
ok      _/zrfiles/cs    7.935s
```

And on actual prometheus data:

```
root@shaprom5:~/projects/go_size# go test -bench=.
testing: warning: no tests to run
Size of /var/lib/prometheus/data is 3594138858768
BenchmarkGolangSize-40          Size of /var/lib/prometheus/data is 3594139155380
Size of /var/lib/prometheus/data is 3594139415758
<... truncated ...>
      50      24473704 ns/op
Size of /var/lib/prometheus/data is 2160102628864
BenchmarkGolangTrueSize-40      Size of /var/lib/prometheus/data is 2160102628864
Size of /var/lib/prometheus/data is 2160102628864
<... truncated ...>
      50      30491314 ns/op
PASS
ok      _/root/projects/go_size 3.439s
```

I'm not sure where I could implement this new approach of calculating sizes in the current codebase, hence I've opened this issue to start a discussion.

_Note: All stats in this post are from boxes running Debian 9._

**Comment by brian-brazil** [comment]
I think what we're currently doing is fine, the filesystem is a black box to us.

**Comment by dipack95** [comment]
The solution I'm proposing is filesystem agnostic as well. We're just retrieving the right size instead of apparent size of the files.

Our current approach is to factor in the compression ratio with the numbers that prometheus reports to us (the apparent file sizes), and then estimate the actual disk space used. This is quite messy imo, as it involves quite a bit of admin overhead to ensure that we aren't running out of space, and the numbers are in sync.

With this solution, we eliminate all of the aforementioned overhead, and have prometheus report the actual space used directly.

**Comment by beorn7** [comment]
The downside of your suggestion is that we introduce a syscall, which is always a bit messy on its own. (To quote one of the [Go proverbs](https://go-proverbs.github.io/): [“Syscall must always be guarded with build tags.](https://www.youtube.com/watch?v=PAAkCSZUG1c&t=11m10s))

The next problem is that regularly stat'ing all the files of a beefier Prometheus instances might start to be costly. There might also be file systems out there for which it is particularly costly. (We cannot know what the filesystem is like. That's probably what @brian-brazil was referring to with the black-box metaphor.)

**Comment by dipack95** [comment]
@beorn7 Your points make sense, thank you for the clarification!
