### ISSUE TITLE
docs outdated on Label offset Table?

### ISSUE THREAD

**Issue by jiacai2050** [prometheus/tsdb#666]
In both [Label Offset Table](https://github.com/prometheus/tsdb/blob/master/docs/format/index.md#label-offset-table) and [Postings Offset Table](https://github.com/prometheus/tsdb/blob/master/docs/format/index.md#postings-offset-table), there is a 4-byte entries field, but in [ReadOffsetTable](https://github.com/prometheus/tsdb/blob/master/index/index.go#L805), read as following order:

1. `cnt := d.Be32()`
2. `keyCount := d.Uvarint()`
3. d.UvarintStr()
4. goto 2 if has more element

It seems that there is no entries in offset table, Am I missing anything?

**Comment by codesome** [comment]
`cnt := d.Be32()` is the `#entries <4b>` field. The `len <4b>` is gobbled up by `encoding.NewDecbufAt(...)`.
