### ISSUE TITLE
Drop sequential block numbering

### ISSUE THREAD

**Issue by fabxc** [prometheus/tsdb#80]
Currently blocks are stored with sequence numbers attached to them that reflect the ordering of their covered intervals (`b-00001`, `b-00002`, ...).
This is mostly nice for running `ls` and seeing the blocks and their size in order but it has little purpose in other ways. Once we start backfilling, we potentially have to rename them all or adding a buffer in front and start with `b-10001` for example. Overall, it might not be worth it.

We might just want to rename the block directory to the ULID that's also shown in their meta.json file.

**Comment by mwitkow** [comment]
Will the ULID be based on the min or max range of the block for the timestamp?

**Comment by Gouthamve** [comment]
I don't think so. So the ulid will be based on **creation-time** of the block (could be a long time in the future due to compactions.): [ref](https://github.com/prometheus/tsdb/blob/7e6961b4ac2930740e0807a57074680c4a4305be/compact.go#L196)

Also we do sort the directories on basis of start time [later](https://github.com/prometheus/tsdb/blob/7e6961b4ac2930740e0807a57074680c4a4305be/compact.go#L131-L133).

**Comment by mwitkow** [comment]
Um, can we make it be a ULIB of min time so it is easy to nuke old blocks
in case of an emergency?

**Comment by mwitkow** [comment]
@fabxc having an ULIB contain the min-time of the Block instead of Block creation time (e.g. during compaction) would also be helpful for the future if dynamic loading/storage of Blocks from a "cold storage" (e.g. S3 or GCS) was to be implemented.

**Comment by fabxc** [comment]
ULID's should have the time of generation as it's done now. Start time is just one piece of meta information. Different use cases need to retrieve different ones, which is why there's the meta.json file. That one is easy enough to retrieve or use to index blocks along other properties.

Pinning it on the start time significantly reduces the ULIDs randomness depending on how the block boundaries are selected.
