### ISSUE TITLE
Discussion: plan support for Blocks archival/retrieval from S3/GCS/other blob storage

### ISSUE THREAD

**Issue by mwitkow** [prometheus/tsdb#86]
The new model of Blocks that have time ranges lends itself to providing long-term storage of Prometheus data. Instead of just keeping Blocks on local storage and deleting old ones past a certain time, it would be possible to have them be pushed to blob storage like S3 or GCS.

The benefits are many:
 * ability to store significantly longer periods of time of data than a single disk provides (e.g. months instead of days)
 * ability to restore Blocks on disk in case disk fails (e.g. a Persistent Volume gets corrupted irrecoverably)

## Upload (milestone 1)
The current compaction algorithm compacts all blocks (including old ones) according to "current-running" parameters of TSDB. We'd need to introduce a marker: `compaction-fully-complete` which means that a given Block should no longer be compacted. Such a block would be subject to asynchronous upload to a blob storage bucket. 

## Recovery of failures (milestone 1)
If TSDB has a blob storage configured, it will sync a configurable (`tsdb.min.synced.horizon=4d`) amount of blocks from blob storage to disk. This means that even if Prometheus is started from scratch, it can serve historic data in case it's local disk gets corrupted.

WAL files are a problem, but I think it is acceptable to tell users that a certain amount of dataloss can happen.

## Dynamic retrieval of past data (milestone 2)
In case a query comes in that is not satisfiable from local-on disk (because the stored Block horizon is not "wide enough"), it should be possible for Prometheus to download Blocks from cold storage on demand. The queries will be slow, but IMHO that's acceptable for old data.

This presents the problem of: how much and how long such "on demand" past data should be kept for. I think a good solution here would be an LRU cache of a configured size. This would allow control of how much disk space should be used.

## Relation to "normal" TSDB
Of course, hacking this into TSDB itself is a bad idea. However, all of the above can be implemented as a wrapper for a real TSDB, with the same interface that TSDB exposes:
 * on init, make sure the "minimum horizon" is satisfied before initializing "real TSDB"
 * in the background, upload fully compacted Blcoks to cold storage
 * on query time, check if it fits in the "real TSDB" and if not do the dynamic fetches.

@fabxc @kdima, what do you think?

**Comment by Gouthamve** [comment]
Hi, I plan to implement backups next week, ref: #4 and here are my thoughts on your idea.

I would be making a CLI tool that would backup all data to an external-folder. The extension of it would be backing up to block storage. Running the tool periodically would mean achievement of milestone 1 and we can restore the complete snapshot incase of a corrupt disk which would be milestone 2.

Now this is all being done by a "tool" external to the tsdb and instead of the tsdb itself, which is what makes sense for me. 

As for dynamic retrieval, I am thinking we could use the same LTS read interface to achieve the same. Make a simple service that retrieves off S3 dynamically, or have someway to mount S3FS and run Prometheus off that mount?

Also, with deletes, we don't know if the block would be recompacted again and we would also need to allow for backfilling.

**Comment by mwitkow** [comment]
Hi, thanks for the comment @Gouthamve. 

>  Running the tool periodically would mean achievement of milestone 1 and we can restore the complete snapshot incase of a corrupt disk which would be milestone 2.

Indeed, that would work if the ULID of the Blocks actually had the `min Series` encoded in it. This way the tool could automatically figure out the range of files to download on startup, without having to scan the contents of the Blocks themselves. Hence the proposal in #80 and the idea of "finally compacted Block".

> As for dynamic retrieval, I am thinking we could use the same LTS read interface to achieve the same.

True, that could be done using the `remote.proto` interface. But it would require that service to run a modified version of TSDB to serve the data and perform other queries. Moving stuff up to the "query, labels and series" level from the "block" level complicates things *a lot* meaning that implementing a archive storage layer becomes really really tedious.

> Make a simple service that retrieves off S3 dynamically, or have someway to mount S3FS and run Prometheus off that mount?

S3FS and other FUSE filesystems are not a good thing to recommend for running in production.

I'm all for generality, and I understand your push back against adding more stuff to TSDB. However, it still feels like if TSDB had hooks for archiving/dynamic retrieval that were satifsiable by a simple interface (proto style, to be similar to remote.proto, but can be easily an RESTful API):

```proto
service TsdbBlockStorage {
  Get(BlockIdRequest) return BlockIdData
  Store(BlockStorageRequest) return Empty
  ListAvailable(BlockRangeRequest) return ListBlockIds
}
```
This would mean that any CLI tool, or any TSDB implementation of dynamic fetching would be generic.

**Comment by opsnull** [comment]
I like the idea.

**Comment by RichiH** [comment]
+ @bastischubert

@Gouthamve and me just talked this over on irc.

````
10:55:21 < RichiH> gouthamve[m]: i am still mulling the failure mode of new storage... assume i have a corrupted block but also valid backups
10:56:04 < RichiH> it should be realtively easy to splice that one block back in; the only possible failure would be to re-create time series in that block which had been deleted
10:56:07 < RichiH> is that correct?
10:56:15 < gouthamve[m]1> Yes.
10:56:21 < gouthamve[m]1> But right now, we don't have any "restore" facility.
10:56:41 < gouthamve[m]1> The only failure recovery mode is "point the prometheus to the backup dir"
10:57:42 < gouthamve[m]1> Which means you lose any data after the last back up. But it should be easy to build what you suggested.
10:59:56 < RichiH> gouthamve[m]: yah, i know it does not exist; but i realized this morning that it should be near trivial to do this
11:00:05 < RichiH> as the blocks don't change
11:00:33 < gouthamve[m]1> Exactly. So funnily it might be the first thing I would build for my project.
11:01:09 < gouthamve[m]1> Ship every block to S3/Minio and then build the restore tool. This restore tool will only pull in the blocks which are missing.
11:01:50 < gouthamve[m]1> Now if a block is corrupted all you do is nuke it and run promtool tsdb restore and you get the missing data from the back up.
11:01:54 < gouthamve[m]1> Sounds good?
11:02:08 < RichiH> gouthamve[m]: ceph does s3 api, so i approve :)
11:02:28 < RichiH> (we are using ceph internally)
11:02:47 < RichiH> gouthamve[m]: you're aware that this is a long term storage for prometheus?
11:02:52 < RichiH> it does replication etc
11:02:54 < gouthamve[m]1> :) Great. Long term storage v0.0.0.0.
11:02:56 < gouthamve[m]1> Exactly
11:02:58 < gouthamve[m]1> I was typing that!!!
11:03:09 < RichiH> that's what i meant yesterday, but i don't think i got that point across
11:03:18 < gouthamve[m]1> Ship to S3 and then manually restore the blocks you need.
11:03:25 < RichiH> no :)
11:03:31 < RichiH> ship to s3
11:03:40 < RichiH> keep an index of what is where
11:03:52 < RichiH> offer promql interface to pull data in as needed
11:04:00 < RichiH> boom, distributed long term prometheus
11:04:02 < RichiH> albeit slow
11:04:19 < gouthamve[m]1> This is one of Fabians ideas and we think it "could" be too slow
11:04:24 < gouthamve[m]1> Needs to be benchmarked.
11:04:38 < RichiH> of course
11:04:43 < gouthamve[m]1> Also, see this: https://github.com/prometheus/tsdb/issues/86
11:04:56 < gouthamve[m]1> Now that I look at it again, it doesn't look so bad :P
11:04:58 < RichiH> but the point is that it's still trivial to restore an actual prometheus with arbitrary time ranges from that
11:05:10 < RichiH> so you always have the slow backup if you need it
11:05:20 < gouthamve[m]1> Yeah.
11:05:53 < gouthamve[m]1> I am going to have a lot of fun building this. Time to get back to intensive code mode.
11:06:11 < RichiH> gouthamve[m]: when will you leave .de?
11:06:22 < gouthamve[m]1> In air in 40mins :P
11:06:45 < gouthamve[m]1> I am tired af now but I think I have more excitement than ever. Thanks for Promcon!
11:07:49 < RichiH> no worries :)
11:08:19 < RichiH> and that's why the (relaxed) face-to-face is so important; it allows for exchange, consideration, and contemplation
11:08:35 < RichiH> fabxc: ^
11:09:52 < RichiH> gouthamve[m]: so if i used the s3 tsdb for, say, accounting data
11:09:59 < RichiH> i would not care about a query taking 20 minutes
11:10:09 < RichiH> i just need the data to be there when i need it
11:11:14 < RichiH> hmm, the next obvious question is if there would be a sane way to have two or more TSDB in one prometheus; both to splice different s3 dumps into one and to factor out important from less important stuff
````

**Comment by krasi-georgiev** [comment]
@gouthamve , @Bplotka all this is now possible with Thanos, right? 
do we still need this issue here?

**Comment by gouthamve** [comment]
I don't think so. Closing this.
