### ISSUE TITLE
Incorrect metadata being populated on deletions

### ISSUE THREAD

**Issue by Gouthamve** [prometheus/tsdb#87]
The numSeries and numSamples values after a block with tombstones is compacted are wrong.

While I have the fix ready for numSeries, [numSamples](https://github.com/prometheus/tsdb/blob/master/compact.go#L177-L179) is a little tricky. When we are [re-encoding a chunk](https://github.com/prometheus/tsdb/blob/master/compact.go#L329-L341) we donot know the number of samples the old chunk holds.

cc @fabxc

**Comment by fabxc** [comment]
First, maybe we should make the beginning of a chunk always a varint of the
number of samples. The XOR encoding does this anyway. We should probably
just drag it out and make it part of the chunk file format. With that, it's
a lot easier to re-count samples on every compaction without decompressing
everything.

Second, we can just drop the stat for now if you feel that's better than
the inconsistency. It's not really being used right now.

**Comment by Gouthamve** [comment]
Closed in #108
