### ISSUE TITLE
Allow fast access to most recent sample

### ISSUE THREAD

**Issue by fabxc** [prometheus/tsdb#9]
For federation in Prometheus we want fast access to the most recent sample. This is currently not served by the interface we have which only allows forward-streaming access to a series for a time window.
That's the interface actually reflecting properly how data is stored in the database. We do have an efficient cache of the most recent sample but that is strictly speaking an implementation detail. Meaning: extending the `SeriesIterator` interface by a `Last()` call would seem like a workaround at best.

First, need for such a fast access should be benchmarked again in context of the new storage. If it turns out to still be necessary, I'm leaning towards exposing the in-memory block type and making it accessible – potentially as yet another interface.
The federation layer would then use this instead of the general `SeriesIterator` interface.

Sounds sane? @beorn7 @brian-brazil

**Comment by brian-brazil** [comment]
With atomicity and staleness handling, which I hope to get in with the new storage for 2.0, I can see this requiring more involved logic which makes considerations around the current implementation largely moot.

Let's get something working, and then benchmark.

**Comment by fabxc** [comment]
Federation does work modulo #10 which can cause duplicate entries for overlapping selectors right now. So yes, this is is a low priority issue for now.

**Comment by beorn7** [comment]
Just two thoughts at this point (not much time to dig deeper):

- The fast access path for the last sample was not only motivated by federation but also by the fact that rule evaluation are often just accessing the last sample of a series.

- Given that allocation churn of the query layer seems a problem right now, I could imagine that a low-alloc access path to the last sample would help here (note that many advanced setups have a huge amount of rule evaluations going on all the time). (This is based on naïve code reading if how the iteration for for federation works. Might be all wrong.)

**Comment by fabxc** [comment]
> The fast access path for the last sample was not only motivated by federation but also by the fact that rule evaluation are often just accessing the last sample of a series. 

To my knowledge rule evaluations are just regular queries and do not make us of the particular storage call. The query engine does not use it internally either.
I'd argue that almost all rule evaluations that are relevant in cost, use time aggregation anyway and it doesn't apply.

> Given that allocation churn of the query layer seems a problem right now, I could imagine that a low-alloc access path to the last sample would help here (note that many advanced setups have a huge amount of rule evaluations going on all the time). (This is based on naïve code reading if how the iteration for for federation works. Might be all wrong.)

Not so much of a problem. Just way higher than it would need to be. The allocs don't relate so much to access but to what the QE allocates itself. v2 also allocates internally when being queried, but that's not happening in v3.

**Comment by beorn7** [comment]
Storage v2 transparently returns an "instant" series iterator for an instant query with a timestamp beyond the end of a series.

But yes, range queries obviously cannot benefit from that.

**Comment by fabxc** [comment]
As per reports federation actually works faster already and there's currently no need for adding complexity of the fast access.
