### ISSUE TITLE
Better heuristic for cutting new chunks

### ISSUE THREAD

**Issue by fabxc** [prometheus/tsdb#93]
Currently we cut a new chunk at 130 samples. If the sampling frequency fits 140 samples into a block, that results in uneven chunks. There a many similar scenarios causing similar imbalances.
The XOR encoding reaches good comression at 30 samples, near-ideal at 60, and certainly ideal at about 120 (c.f. http://www.vldb.org/pvldb/vol8/p1816-teller.pdf, page 1820).

I would propose to make a decision at the 30th sample of every chunk.  We look at the chunk's average sample frequency so far and extrapolate how many more samples will fit until the end of the block.
We then check how many idealized chunks of 120 samples are necessary to fill it. We round that down to err on the side of better compression and determine the end timestamp of the chunk based on that.

Naive formula:

```
s  = start time of current chunk
s' = start time of next chunk
m  = max timestamp for the block
r  = time range of chunk so far

s' = s + (m - s) / floor((m - s) / r / 4)
```

There are probably smarter heuristics. But this one is cheap, just runs once per chunk and does what we want most of the time I think.

**Comment by Gouthamve** [comment]
Closed via #94
